pub const FREE_FEATURES: &[&str] = &["hex_editor", "report_export"];

pub const TRIAL_FEATURES: &[&str] = &[
    "hex_editor",
    "registry_viewer",
    "timeline",
    "browser_history",
    "prefetch_parser",
    "lnk_parser",
    "shellbags",
    "evtx_parser",
    "content_search",
    "file_carving",
    "hash_sets",
    "report_export",
    "audit_log",
    "plugins",
    "forge_integration",
    "compare",
    "vss_access",
];

pub const PRO_FEATURES: &[&str] = &[
    "hex_editor",
    "registry_viewer",
    "timeline",
    "browser_history",
    "prefetch_parser",
    "lnk_parser",
    "shellbags",
    "evtx_parser",
    "content_search",
    "file_carving",
    "hash_sets",
    "report_export",
    "audit_log",
    "compare",
    "vss_access",
];

pub const ENTERPRISE_FEATURES: &[&str] = &[
    "hex_editor",
    "registry_viewer",
    "timeline",
    "browser_history",
    "prefetch_parser",
    "lnk_parser",
    "shellbags",
    "evtx_parser",
    "content_search",
    "file_carving",
    "hash_sets",
    "report_export",
    "audit_log",
    "plugins",
    "forge_integration",
    "compare",
    "vss_access",
];
