pub mod developer;
pub mod dropbox;
pub mod enterprise;
pub mod gdrive;
pub mod google_takeout;
pub mod graph_api;
pub mod icloud;
pub mod office365;
pub mod platforms;

pub use developer::DeveloperForensics;
pub use dropbox::DropboxParser;
pub use enterprise::EnterpriseWorkspaceParser;
pub use gdrive::GoogleDriveParser;
pub use google_takeout::GoogleTakeoutParser;
pub use graph_api::GraphApiParser;
pub use icloud::IcloudSyncParser;
pub use office365::Office365Parser;
pub use platforms::CloudSaaSParser;
