//! Agency branding for report output (UX-2).
//!
//! Pure-Rust TOML-backed configuration layer applied to every Strata
//! HTML report. Logos are embedded as base64 data URIs — no external
//! file references in rendered reports.
//!
//! Zero `unwrap`, zero `unsafe`, zero `println!` per CLAUDE.md.

use serde::{Deserialize, Serialize};
use std::fs;
use std::path::Path;
use thiserror::Error;

pub const MAX_LOGO_BYTES: usize = 2 * 1024 * 1024;

#[derive(Debug, Error)]
pub enum BrandingError {
    #[error("io: {0}")]
    Io(#[from] std::io::Error),
    #[error("logo too large: {0} bytes (max {MAX_LOGO_BYTES})")]
    LogoTooLarge(usize),
    #[error("invalid: {0}")]
    Invalid(String),
}

#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct ReportBranding {
    pub agency_name: String,
    pub agency_short: String,
    pub office_name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub logo_data: Option<Vec<u8>>,
    pub logo_mime: Option<String>,
    pub primary_color: Option<String>,
    pub footer_text: Option<String>,
    pub examiner_name: String,
    pub examiner_title: Option<String>,
    pub examiner_credentials: Option<String>,
    pub examiner_id: Option<String>,
    pub case_number: Option<String>,
    pub signature_block: Option<String>,
    #[serde(default)]
    pub include_strata_watermark: bool,
}

impl ReportBranding {
    pub fn set_logo(&mut self, bytes: Vec<u8>, mime: &str) -> Result<(), BrandingError> {
        if bytes.len() > MAX_LOGO_BYTES {
            return Err(BrandingError::LogoTooLarge(bytes.len()));
        }
        if mime != "image/png" && mime != "image/svg+xml" {
            return Err(BrandingError::Invalid(format!(
                "unsupported logo mime: {}",
                mime
            )));
        }
        self.logo_data = Some(bytes);
        self.logo_mime = Some(mime.to_string());
        Ok(())
    }

    /// Render the branded HTML header block.
    pub fn render_header_html(&self, case_number: &str, date: &str) -> String {
        let mut out = String::new();
        out.push_str("<header class=\"strata-branded\">\n");
        if let (Some(bytes), Some(mime)) = (&self.logo_data, &self.logo_mime) {
            let encoded = base64_encode(bytes);
            out.push_str(&format!(
                "  <img class=\"agency-logo\" alt=\"{}\" src=\"data:{};base64,{}\" />\n",
                escape(&self.agency_short),
                escape(mime),
                encoded
            ));
        }
        out.push_str("  <div class=\"agency-info\">\n");
        out.push_str(&format!(
            "    <div class=\"agency-name\">{}</div>\n",
            escape(&self.agency_name)
        ));
        if let Some(office) = &self.office_name {
            out.push_str(&format!("    <div class=\"office\">{}</div>\n", escape(office)));
        }
        out.push_str("    <hr/>\n");
        out.push_str(
            "    <div class=\"title\">DIGITAL FORENSIC EXAMINATION REPORT</div>\n",
        );
        out.push_str(&format!(
            "    <div class=\"meta\">Case: {} | Date: {}</div>\n",
            escape(case_number),
            escape(date)
        ));
        out.push_str("  </div>\n</header>\n");
        out
    }

    pub fn render_footer_html(&self) -> String {
        let mut out = String::from("<footer class=\"strata-branded\">\n");
        if let Some(text) = &self.footer_text {
            out.push_str(&format!("  <div>{}</div>\n", escape(text)));
        }
        if let Some(sig) = &self.signature_block {
            out.push_str(&format!("  <pre class=\"signature\">{}</pre>\n", escape(sig)));
        }
        if self.include_strata_watermark {
            out.push_str("  <div class=\"watermark\">Generated by Strata Forensic Platform</div>\n");
        }
        out.push_str("</footer>\n");
        out
    }

    pub fn save(&self, path: &Path) -> Result<(), BrandingError> {
        let toml = toml_encode(self)?;
        if let Some(parent) = path.parent() {
            if !parent.exists() {
                fs::create_dir_all(parent)?;
            }
        }
        fs::write(path, toml)?;
        Ok(())
    }

    pub fn load(path: &Path) -> Result<Self, BrandingError> {
        let body = fs::read_to_string(path)?;
        toml_decode(&body)
    }
}

/// Minimal TOML encoder — we emit only string / bool / integer / array
/// <u8> shapes this config actually uses.
fn toml_encode(b: &ReportBranding) -> Result<String, BrandingError> {
    let mut out = String::new();
    out.push_str(&kv_str("agency_name", &b.agency_name));
    out.push_str(&kv_str("agency_short", &b.agency_short));
    if let Some(v) = &b.office_name {
        out.push_str(&kv_str("office_name", v));
    }
    if let Some(v) = &b.logo_mime {
        out.push_str(&kv_str("logo_mime", v));
    }
    if let Some(v) = &b.logo_data {
        out.push_str(&format!("logo_data_b64 = \"{}\"\n", base64_encode(v)));
    }
    if let Some(v) = &b.primary_color {
        out.push_str(&kv_str("primary_color", v));
    }
    if let Some(v) = &b.footer_text {
        out.push_str(&kv_str("footer_text", v));
    }
    out.push_str(&kv_str("examiner_name", &b.examiner_name));
    if let Some(v) = &b.examiner_title {
        out.push_str(&kv_str("examiner_title", v));
    }
    if let Some(v) = &b.examiner_credentials {
        out.push_str(&kv_str("examiner_credentials", v));
    }
    if let Some(v) = &b.examiner_id {
        out.push_str(&kv_str("examiner_id", v));
    }
    if let Some(v) = &b.case_number {
        out.push_str(&kv_str("case_number", v));
    }
    if let Some(v) = &b.signature_block {
        out.push_str(&kv_str("signature_block", v));
    }
    out.push_str(&format!(
        "include_strata_watermark = {}\n",
        b.include_strata_watermark
    ));
    Ok(out)
}

fn toml_decode(body: &str) -> Result<ReportBranding, BrandingError> {
    let mut b = ReportBranding::default();
    for raw in body.lines() {
        let line = raw.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let Some((key, rest)) = line.split_once('=') else {
            continue;
        };
        let key = key.trim();
        let value = rest.trim();
        if let Some(inner) = strip_quotes(value) {
            match key {
                "agency_name" => b.agency_name = inner,
                "agency_short" => b.agency_short = inner,
                "office_name" => b.office_name = Some(inner),
                "logo_mime" => b.logo_mime = Some(inner),
                "logo_data_b64" => b.logo_data = base64_decode(&inner),
                "primary_color" => b.primary_color = Some(inner),
                "footer_text" => b.footer_text = Some(inner),
                "examiner_name" => b.examiner_name = inner,
                "examiner_title" => b.examiner_title = Some(inner),
                "examiner_credentials" => b.examiner_credentials = Some(inner),
                "examiner_id" => b.examiner_id = Some(inner),
                "case_number" => b.case_number = Some(inner),
                "signature_block" => b.signature_block = Some(inner),
                _ => {}
            }
        } else if key == "include_strata_watermark" {
            b.include_strata_watermark = value == "true";
        }
    }
    Ok(b)
}

fn kv_str(k: &str, v: &str) -> String {
    format!("{} = \"{}\"\n", k, v.replace('"', "\\\""))
}

fn strip_quotes(s: &str) -> Option<String> {
    let s = s.strip_prefix('"')?;
    let s = s.strip_suffix('"')?;
    Some(s.replace("\\\"", "\""))
}

fn escape(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

const B64: &[u8; 64] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";

fn base64_encode(bytes: &[u8]) -> String {
    let mut out = String::with_capacity(bytes.len().div_ceil(3) * 4);
    let mut i = 0;
    while i + 3 <= bytes.len() {
        let n = ((bytes[i] as u32) << 16) | ((bytes[i + 1] as u32) << 8) | (bytes[i + 2] as u32);
        out.push(B64[((n >> 18) & 0x3F) as usize] as char);
        out.push(B64[((n >> 12) & 0x3F) as usize] as char);
        out.push(B64[((n >> 6) & 0x3F) as usize] as char);
        out.push(B64[(n & 0x3F) as usize] as char);
        i += 3;
    }
    let remaining = bytes.len() - i;
    if remaining == 1 {
        let n = (bytes[i] as u32) << 16;
        out.push(B64[((n >> 18) & 0x3F) as usize] as char);
        out.push(B64[((n >> 12) & 0x3F) as usize] as char);
        out.push('=');
        out.push('=');
    } else if remaining == 2 {
        let n = ((bytes[i] as u32) << 16) | ((bytes[i + 1] as u32) << 8);
        out.push(B64[((n >> 18) & 0x3F) as usize] as char);
        out.push(B64[((n >> 12) & 0x3F) as usize] as char);
        out.push(B64[((n >> 6) & 0x3F) as usize] as char);
        out.push('=');
    }
    out
}

fn base64_decode(s: &str) -> Option<Vec<u8>> {
    let clean: String = s.chars().filter(|c| !c.is_whitespace()).collect();
    let mut decoded = Vec::with_capacity(clean.len() / 4 * 3);
    let mut buf = 0u32;
    let mut bits = 0u32;
    for c in clean.chars() {
        if c == '=' {
            break;
        }
        let v = B64.iter().position(|b| *b as char == c)? as u32;
        buf = (buf << 6) | v;
        bits += 6;
        if bits >= 8 {
            bits -= 8;
            decoded.push(((buf >> bits) & 0xFF) as u8);
        }
    }
    Some(decoded)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample() -> ReportBranding {
        ReportBranding {
            agency_name: "Federal Bureau of Investigation".into(),
            agency_short: "FBI".into(),
            office_name: Some("Cyber Division".into()),
            logo_data: None,
            logo_mime: None,
            primary_color: Some("#003087".into()),
            footer_text: Some("For Official Use Only".into()),
            examiner_name: "Jane Doe".into(),
            examiner_title: Some("Special Agent".into()),
            examiner_credentials: Some("GCFE".into()),
            examiner_id: Some("12345".into()),
            case_number: Some("FBI-2026-0001".into()),
            signature_block: None,
            include_strata_watermark: true,
        }
    }

    #[test]
    fn render_header_includes_agency_and_case_info() {
        let html = sample().render_header_html("FBI-2026-0001", "2026-04-16");
        assert!(html.contains("Federal Bureau of Investigation"));
        assert!(html.contains("Cyber Division"));
        assert!(html.contains("Case: FBI-2026-0001"));
    }

    #[test]
    fn set_logo_rejects_oversize_and_bad_mime() {
        let mut b = sample();
        let huge = vec![0u8; MAX_LOGO_BYTES + 1];
        assert!(matches!(b.set_logo(huge, "image/png"), Err(BrandingError::LogoTooLarge(_))));
        assert!(matches!(b.set_logo(vec![0u8; 4], "image/jpeg"), Err(BrandingError::Invalid(_))));
        assert!(b.set_logo(vec![0xDE, 0xAD, 0xBE, 0xEF], "image/png").is_ok());
    }

    #[test]
    fn render_header_embeds_logo_as_data_uri() {
        let mut b = sample();
        b.set_logo(vec![0xDE, 0xAD, 0xBE, 0xEF], "image/png").expect("logo");
        let html = b.render_header_html("C", "D");
        assert!(html.contains("data:image/png;base64,"));
        assert!(html.contains("3q2+7w==") || html.contains("3q2+"));
    }

    #[test]
    fn save_and_load_round_trip() {
        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path().join("branding.toml");
        let b = sample();
        b.save(&path).expect("save");
        let loaded = ReportBranding::load(&path).expect("load");
        assert_eq!(loaded.agency_name, b.agency_name);
        assert_eq!(loaded.examiner_id, b.examiner_id);
        assert!(loaded.include_strata_watermark);
    }

    #[test]
    fn base64_round_trip() {
        let original = b"Hello, forensic world!";
        let enc = base64_encode(original);
        let dec = base64_decode(&enc).expect("decode");
        assert_eq!(dec, original);
    }

    #[test]
    fn render_footer_respects_watermark_flag() {
        let mut b = sample();
        b.include_strata_watermark = false;
        assert!(!b.render_footer_html().contains("Strata Forensic Platform"));
        b.include_strata_watermark = true;
        assert!(b.render_footer_html().contains("Strata Forensic Platform"));
    }
}
