import { useEffect, useState } from 'react'
import { useAppStore } from '../store/appStore'
import EmptyState from '../components/EmptyState'
import { getArtifacts, runPlugin, type Artifact } from '../ipc'

export default function ChargesView() {
  const evidenceLoaded = useAppStore((s) => s.evidenceLoaded)
  const evidenceId = useAppStore((s) => s.evidenceId)
  const [chargeArtifacts, setChargeArtifacts] = useState<Artifact[]>([])
  const [running, setRunning] = useState(false)
  const [status, setStatus] = useState<string | null>(null)

  const refresh = async () => {
    if (!evidenceId) return
    const res = await getArtifacts(evidenceId, 'Advisory')
    setChargeArtifacts(
      res.artifacts.filter((a) =>
        /charge|offense/i.test(`${a.name} ${a.value}`),
      ),
    )
  }

  useEffect(() => {
    void refresh()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [evidenceId])

  if (!evidenceLoaded || !evidenceId) {
    return (
      <EmptyState
        icon={'\u{2696}'}
        title="Charge Analysis"
        subtitle="Load evidence and run the Advisory plugin"
      />
    )
  }

  const handleRunAdvisory = async () => {
    if (!evidenceId || running) return
    setRunning(true)
    setStatus('Running Advisory plugin...')
    const result = await runPlugin('Advisory Analytics', evidenceId)
    setRunning(false)
    setStatus(result.success ? `Advisory complete - ${result.artifact_count} artifacts` : 'Failed')
    await refresh()
  }

  return (
    <div
      style={{
        flex: 1,
        background: 'var(--bg-base)',
        padding: 8,
        display: 'flex',
      }}
    >
      <div
        className="bubble"
        style={{
          flex: 1,
          display: 'flex',
          flexDirection: 'column',
        }}
      >
        <div
          style={{
            padding: '10px 14px',
            fontSize: 11,
            color: 'var(--text-muted)',
            textTransform: 'uppercase',
            letterSpacing: '0.1em',
            fontWeight: 700,
            borderBottom: '1px solid var(--border-sub)',
          }}
        >
          Charge Analysis
        </div>
        <div style={{ flex: 1, overflowY: 'auto', padding: 24 }}>
          {chargeArtifacts.length > 0 ? (
            <div>
              <div
                style={{
                  fontSize: 10,
                  color: 'var(--sus)',
                  background: 'rgba(184,120,64,0.08)',
                  border: '1px solid rgba(184,120,64,0.3)',
                  borderRadius: 4,
                  padding: '8px 12px',
                  marginBottom: 16,
                  lineHeight: 1.5,
                }}
              >
                {'⚠'} Charge suggestions are advisory ML output. They require
                attorney review before any legal action.
              </div>
              {chargeArtifacts.map((a) => (
                <div
                  key={a.id}
                  style={{
                    padding: 12,
                    marginBottom: 8,
                    background: 'var(--bg-elevated)',
                    border: '1px solid var(--border)',
                    borderLeft: '3px solid var(--carved)',
                    borderRadius: 4,
                  }}
                >
                  <div
                    style={{
                      fontSize: 13,
                      fontWeight: 700,
                      color: 'var(--text-1)',
                      marginBottom: 4,
                    }}
                  >
                    {a.name}
                  </div>
                  <div style={{ fontSize: 12, color: 'var(--text-2)', lineHeight: 1.5 }}>
                    {a.value}
                  </div>
                  {a.mitre_technique && (
                    <div
                      style={{
                        marginTop: 6,
                        fontSize: 10,
                        fontFamily: 'monospace',
                        color: 'var(--carved)',
                      }}
                    >
                      MITRE: {a.mitre_technique}
                    </div>
                  )}
                </div>
              ))}
            </div>
          ) : (
            <Stub
              icon={'\u{2696}'}
              title="No charge suggestions yet"
              body="Charge analysis is generated by the Advisory plugin from detected artifacts and MITRE techniques."
              cta={running ? 'RUNNING ADVISORY...' : 'RUN ADVISORY PLUGIN'}
              onCta={handleRunAdvisory}
              disabled={running}
              status={status}
              footer={[
                'Supported frameworks:',
                '· Federal criminal statutes',
                '· UCMJ Articles',
                '· State law cross-reference (future)',
              ]}
            />
          )}
        </div>
      </div>
    </div>
  )
}

export function Stub({
  icon,
  title,
  body,
  cta,
  onCta,
  disabled,
  status,
  footer,
}: {
  icon: string
  title: string
  body: string
  cta: string
  onCta: () => void
  disabled?: boolean
  status?: string | null
  footer?: string[]
}) {
  return (
    <div style={{ maxWidth: 640, margin: '0 auto', textAlign: 'left' }}>
      <div style={{ fontSize: 32, marginBottom: 12 }}>{icon}</div>
      <div
        style={{
          fontSize: 18,
          fontWeight: 700,
          color: 'var(--text-1)',
          marginBottom: 8,
        }}
      >
        {title}
      </div>
      <div
        style={{
          fontSize: 13,
          color: 'var(--text-2)',
          lineHeight: 1.6,
          marginBottom: 16,
        }}
      >
        {body}
      </div>
      <button
        onClick={onCta}
        disabled={disabled}
        className="btn-primary"
        style={{
          padding: '8px 16px',
          fontSize: 11,
          fontFamily: 'monospace',
          fontWeight: 700,
          letterSpacing: '0.08em',
        }}
      >
        {cta}
      </button>
      {status && (
        <div
          style={{
            marginTop: 10,
            fontSize: 11,
            color: 'var(--text-muted)',
            fontFamily: 'monospace',
          }}
        >
          {status}
        </div>
      )}
      {footer && (
        <div
          style={{
            marginTop: 24,
            paddingTop: 16,
            borderTop: '1px solid var(--border-sub)',
            fontSize: 11,
            color: 'var(--text-muted)',
            lineHeight: 1.8,
          }}
        >
          {footer.map((line) => (
            <div key={line}>{line}</div>
          ))}
        </div>
      )}
    </div>
  )
}
