use crate::history::{Conversation, MessageRole};

/// Export a conversation as plain text.
pub fn export_text(conv: &Conversation) -> String {
    let mut out = String::new();
    out.push_str("STRATA FORGE — Analysis Session\n");
    out.push_str("================================\n");
    if let Some(ref case) = conv.case_name {
        out.push_str(&format!("Case: {}\n", case));
    }
    out.push_str(&format!("Session: {}\n", conv.title));
    out.push_str(&format!("Created: {} UTC\n", conv.created_at));
    out.push_str(&format!("Messages: {}\n", conv.messages.len()));
    out.push('\n');

    for msg in &conv.messages {
        let role_str = match msg.role {
            MessageRole::User => "EXAMINER",
            MessageRole::Assistant => "FORGE",
        };
        out.push_str(&format!("[{}] {} UTC\n", role_str, msg.timestamp));
        out.push_str(&msg.content);
        out.push_str("\n\n");
    }

    // MITRE summary
    let all_refs: Vec<String> = conv
        .messages
        .iter()
        .flat_map(|m| m.mitre_refs.iter().cloned())
        .collect::<std::collections::HashSet<_>>()
        .into_iter()
        .collect();

    if !all_refs.is_empty() {
        out.push_str("MITRE ATT&CK References\n");
        out.push_str("-----------------------\n");
        for r in &all_refs {
            out.push_str(&format!("  {}\n", r));
        }
    }

    out
}

/// Export a conversation as markdown.
pub fn export_markdown(conv: &Conversation) -> String {
    let mut out = String::new();
    out.push_str("# Strata Forge — Analysis Session\n\n");
    if let Some(ref case) = conv.case_name {
        out.push_str(&format!("**Case:** {}\n\n", case));
    }
    out.push_str(&format!("**Session:** {}\n\n", conv.title));
    out.push_str(&format!("**Created:** {} UTC\n\n", conv.created_at));
    out.push_str("---\n\n");

    for msg in &conv.messages {
        let role_str = match msg.role {
            MessageRole::User => "Examiner",
            MessageRole::Assistant => "Forge",
        };
        out.push_str(&format!("### {} — {} UTC\n\n", role_str, msg.timestamp));

        // Render context snapshot if present
        if let Some(ref ctx) = msg.context_snapshot {
            if !ctx.is_empty() {
                out.push_str("> **Evidence Context:**\n");
                if let Some(ref p) = ctx.file_path {
                    out.push_str(&format!("> File: `{}`\n", p));
                }
                if let Some(ref h) = ctx.file_hash_sha256 {
                    out.push_str(&format!("> SHA-256: `{}`\n", h));
                }
                out.push_str(">\n\n");
            }
        }

        out.push_str(&msg.content);
        out.push_str("\n\n");
    }

    // MITRE summary
    let all_refs: Vec<String> = conv
        .messages
        .iter()
        .flat_map(|m| m.mitre_refs.iter().cloned())
        .collect::<std::collections::HashSet<_>>()
        .into_iter()
        .collect();

    if !all_refs.is_empty() {
        out.push_str("---\n\n## MITRE ATT&CK References\n\n");
        for r in &all_refs {
            out.push_str(&format!("- `{}`\n", r));
        }
    }

    out.push_str("\n---\n\n*Generated by Strata Forge v0.1.0*\n");
    out
}

/// Export a conversation as self-contained HTML.
pub fn export_html(conv: &Conversation) -> String {
    let mut out = String::new();
    out.push_str("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n");
    out.push_str("<meta charset=\"utf-8\">\n");
    out.push_str("<title>Strata Forge Analysis Report</title>\n");
    out.push_str("<style>\n");
    out.push_str("body { font-family: 'Segoe UI', sans-serif; background: #0a0b0e; color: #e6e8eb; max-width: 900px; margin: 40px auto; padding: 20px; }\n");
    out.push_str("h1 { color: #f97316; border-bottom: 2px solid #f97316; padding-bottom: 8px; }\n");
    out.push_str("h2 { color: #94a3b8; }\n");
    out.push_str(".meta { color: #8b949e; font-size: 0.9em; margin-bottom: 20px; }\n");
    out.push_str(".msg { margin: 16px 0; padding: 12px 16px; border-radius: 8px; border: 1px solid #30363d; }\n");
    out.push_str(".user { background: #1c2128; border-left: 3px solid #f97316; }\n");
    out.push_str(".assistant { background: #161b22; border-left: 3px solid #00d4ff; }\n");
    out.push_str(".role { font-weight: 600; font-size: 0.75em; text-transform: uppercase; letter-spacing: 1px; margin-bottom: 6px; }\n");
    out.push_str(".role-user { color: #f97316; }\n");
    out.push_str(".role-ai { color: #00d4ff; }\n");
    out.push_str(".ts { color: #8b949e; font-size: 0.7em; float: right; }\n");
    out.push_str(".content { white-space: pre-wrap; line-height: 1.6; }\n");
    out.push_str(
        ".mitre { background: #1a1a2e; padding: 12px; border-radius: 6px; margin-top: 20px; }\n",
    );
    out.push_str(".mitre code { background: #2d2d44; padding: 2px 6px; border-radius: 3px; color: #f97316; }\n");
    out.push_str("hr { border: none; border-top: 1px solid #30363d; margin: 24px 0; }\n");
    out.push_str("</style>\n</head>\n<body>\n");

    out.push_str("<h1>Strata Forge Analysis Report</h1>\n");
    out.push_str("<div class=\"meta\">\n");
    if let Some(ref case) = conv.case_name {
        out.push_str(&format!(
            "<strong>Case:</strong> {} &nbsp;|&nbsp; ",
            esc(case)
        ));
    }
    out.push_str(&format!(
        "<strong>Session:</strong> {} &nbsp;|&nbsp; <strong>Created:</strong> {} UTC",
        esc(&conv.title),
        esc(&conv.created_at)
    ));
    out.push_str("</div>\n<hr>\n");

    for msg in &conv.messages {
        let (class, role_class, role_label) = match msg.role {
            MessageRole::User => ("user", "role-user", "Examiner"),
            MessageRole::Assistant => ("assistant", "role-ai", "Forge"),
        };
        out.push_str(&format!("<div class=\"msg {}\">\n", class));
        out.push_str(&format!(
            "<div class=\"role {}\"><span class=\"ts\">{} UTC</span>{}</div>\n",
            role_class,
            esc(&msg.timestamp),
            role_label
        ));
        out.push_str(&format!(
            "<div class=\"content\">{}</div>\n",
            esc(&msg.content)
        ));
        out.push_str("</div>\n");
    }

    // MITRE summary
    let all_refs: Vec<String> = conv
        .messages
        .iter()
        .flat_map(|m| m.mitre_refs.iter().cloned())
        .collect::<std::collections::HashSet<_>>()
        .into_iter()
        .collect();

    if !all_refs.is_empty() {
        out.push_str("<hr>\n<div class=\"mitre\">\n<h2>MITRE ATT&CK References</h2>\n");
        for r in &all_refs {
            out.push_str(&format!("<code>{}</code> ", esc(r)));
        }
        out.push_str("\n</div>\n");
    }

    out.push_str("<hr>\n<p style=\"color:#8b949e;font-size:0.8em;\">Generated by Strata Forge v0.1.0 — Wolfmark Systems LLC</p>\n");
    out.push_str("</body>\n</html>\n");
    out
}

fn esc(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}
