fn s(v: &str) -> String {
    v.to_string()
}
fn sv(v: &[&str]) -> Vec<String> {
    v.iter().map(|x| x.to_string()).collect()
}

pub fn all_artifacts() -> Vec<super::ForensicArtifact> {
    vec![
        super::ForensicArtifact {
            name: s("Prefetch"),
            path: s("C:\\Windows\\Prefetch\\*.pf"),
            description: s("Windows Prefetch files record metadata about program execution including run count, last run times, and referenced files/directories."),
            forensic_value: s("Proves program execution with timestamps. Shows up to 8 last execution times (Win10+). Run count indicates frequency of use."),
            interpretation: s("Filename format: EXECUTABLE-HASH.pf. Hash is based on path. Multiple .pf files for same exe = different source paths. Creation time = first execution. Modification time = last execution."),
            tools: sv(&["PECmd (Eric Zimmerman)", "WinPrefetchView (NirSoft)", "Autopsy", "Strata Tree"]),
        },
        super::ForensicArtifact {
            name: s("Shellbags"),
            path: s("NTUSER.DAT\\Software\\Microsoft\\Windows\\Shell\\BagMRU and NTUSER.DAT\\Software\\Microsoft\\Windows\\Shell\\Bags; UsrClass.dat\\Local Settings\\Software\\Microsoft\\Windows\\Shell\\BagMRU"),
            description: s("Shellbags record folder access and Explorer window positions. Persist even after folders are deleted."),
            forensic_value: s("Proves a user navigated to a folder in Explorer, even on removable media or network shares. Timestamps show first and last access."),
            interpretation: s("BagMRU contains the tree hierarchy. Bags contains display settings. Entries persist after folder deletion, proving historical access to paths including USB drives and network shares."),
            tools: sv(&["ShellBags Explorer (Eric Zimmerman)", "Registry Explorer", "Strata Tree"]),
        },
        super::ForensicArtifact {
            name: s("LNK Files"),
            path: s("C:\\Users\\<user>\\AppData\\Roaming\\Microsoft\\Windows\\Recent\\*.lnk; C:\\Users\\<user>\\Desktop\\*.lnk"),
            description: s("Windows shortcut files created when a user opens a file. Contain target path, MAC timestamps, volume serial, and sometimes NetBIOS name."),
            forensic_value: s("Proves file access with timestamps. Contains original target path even if file is deleted. Volume serial number can link to specific USB devices."),
            interpretation: s("Creation time = first time file was opened. Modification time = last time shortcut was updated. Target path shows original file location. Volume info shows drive type and serial."),
            tools: sv(&["LECmd (Eric Zimmerman)", "LNK Parser", "Autopsy", "Strata Tree"]),
        },
        super::ForensicArtifact {
            name: s("Jump Lists"),
            path: s("C:\\Users\\<user>\\AppData\\Roaming\\Microsoft\\Windows\\Recent\\AutomaticDestinations\\*.automaticDestinations-ms; C:\\Users\\<user>\\AppData\\Roaming\\Microsoft\\Windows\\Recent\\CustomDestinations\\*.customDestinations-ms"),
            description: s("Jump Lists track recently and frequently accessed files per application via the taskbar. Stored as OLE compound files."),
            forensic_value: s("Shows which files were opened by which application. Automatic lists show recent files. Custom lists show pinned/frequent items."),
            interpretation: s("AppID in filename maps to specific application. Each entry contains LNK data with full target path, MAC times, and volume info. Entries persist after file deletion."),
            tools: sv(&["JLECmd (Eric Zimmerman)", "JumpList Explorer", "Autopsy"]),
        },
        super::ForensicArtifact {
            name: s("Browser History"),
            path: s("Chrome: C:\\Users\\<user>\\AppData\\Local\\Google\\Chrome\\User Data\\Default\\History; Firefox: C:\\Users\\<user>\\AppData\\Roaming\\Mozilla\\Firefox\\Profiles\\*.default*\\places.sqlite; Edge: C:\\Users\\<user>\\AppData\\Local\\Microsoft\\Edge\\User Data\\Default\\History"),
            description: s("Browser history databases (SQLite) contain URLs visited, timestamps, visit counts, and download records."),
            forensic_value: s("Proves web browsing activity with timestamps. Downloads table shows file downloads. Can reveal C2 communication, phishing, or data exfiltration."),
            interpretation: s("Chrome/Edge: urls table + visits table joined by url_id. Firefox: moz_places + moz_historyvisits. Timestamps in Chrome are WebKit epoch (microseconds since 1601-01-01). Firefox uses PRTime (microseconds since Unix epoch)."),
            tools: sv(&["DB Browser for SQLite", "Hindsight (Chrome)", "Autopsy", "Strata Tree"]),
        },
        super::ForensicArtifact {
            name: s("Windows Event Logs"),
            path: s("C:\\Windows\\System32\\winevt\\Logs\\*.evtx"),
            description: s("Windows Event Logs record system, security, and application events in EVTX format."),
            forensic_value: s("Security.evtx: logon events (4624/4625), process creation (4688), account management (4720/4722/4726). System.evtx: service installs (7045), driver loads. PowerShell: 4103/4104 script block logging."),
            interpretation: s("Key event IDs: 4624 (logon), 4625 (failed logon), 4648 (explicit creds), 4672 (special privs), 4688 (process create), 4698 (scheduled task), 7045 (service install), 1102 (log cleared). Logon types: 2=interactive, 3=network, 10=RDP."),
            tools: sv(&["Event Log Explorer", "EvtxECmd (Eric Zimmerman)", "Chainsaw", "Strata Tree"]),
        },
        super::ForensicArtifact {
            name: s("Registry Run Keys"),
            path: s("HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run; HKCU\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run; HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\RunOnce"),
            description: s("Registry Run keys specify programs to execute at user logon or system startup. Primary persistence mechanism."),
            forensic_value: s("Identifies persistence mechanisms. Any unexpected executable in Run keys is potentially malicious."),
            interpretation: s("Values contain command lines executed at logon. Check for encoded PowerShell, paths to temp directories, or unsigned executables. RunOnce entries auto-delete after execution."),
            tools: sv(&["Registry Explorer (Eric Zimmerman)", "RegRipper", "Autoruns (Sysinternals)", "Strata Tree"]),
        },
        super::ForensicArtifact {
            name: s("AppCompatCache (ShimCache)"),
            path: s("SYSTEM\\CurrentControlSet\\Control\\Session Manager\\AppCompatCache\\AppCompatCache"),
            description: s("Application Compatibility Cache records metadata about executables the OS has seen, including path and last modification timestamp."),
            forensic_value: s("Proves an executable existed on the system. Does NOT prove execution on Win10+ (only proves the file was seen by the OS). On Win7, an execution flag exists."),
            interpretation: s("Entries are ordered by most-recently-seen. Contains full path and $STANDARD_INFORMATION last modified time. Absence does NOT disprove execution. Cache is written on shutdown."),
            tools: sv(&["AppCompatCacheParser (Eric Zimmerman)", "ShimCacheParser", "RegRipper"]),
        },
        super::ForensicArtifact {
            name: s("AmCache.hve"),
            path: s("C:\\Windows\\AppCompat\\Programs\\Amcache.hve"),
            description: s("AmCache is a registry hive that tracks application execution, driver installation, and program installation with SHA-1 hashes."),
            forensic_value: s("Proves execution with SHA-1 hash of the executable. Contains full path, file size, publisher, version, and first execution timestamp."),
            interpretation: s("Key: Root\\InventoryApplicationFile. Contains FileId (SHA-1), LinkDate (compile time), Name, Publisher, Size, Version. Timestamps in registry key last write time. Programs subkey tracks installed software."),
            tools: sv(&["AmcacheParser (Eric Zimmerman)", "Registry Explorer", "RegRipper"]),
        },
        super::ForensicArtifact {
            name: s("UserAssist"),
            path: s("NTUSER.DAT\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\UserAssist"),
            description: s("UserAssist records programs launched via Explorer shell (GUI execution). Values are ROT13 encoded."),
            forensic_value: s("Proves GUI-based program execution with run count and last execution timestamp. Only records Explorer-launched programs, not command-line execution."),
            interpretation: s("GUIDs under UserAssist correspond to different tracking categories. Values are ROT13 of the program path. Data contains run count (offset 4, DWORD) and last execution time (offset 60, FILETIME). Focus count and focus time also recorded."),
            tools: sv(&["UserAssist (Didier Stevens)", "Registry Explorer", "RegRipper"]),
        },
        super::ForensicArtifact {
            name: s("BAM/DAM"),
            path: s("SYSTEM\\CurrentControlSet\\Services\\bam\\State\\UserSettings\\<SID>; SYSTEM\\CurrentControlSet\\Services\\dam\\State\\UserSettings\\<SID>"),
            description: s("Background Activity Moderator tracks program execution with full path and last execution timestamp. Available Win10 1709+."),
            forensic_value: s("Proves execution with timestamp. Contains full device path and last execution time per user SID."),
            interpretation: s("Each value is a device path (\\Device\\HarddiskVolume#\\path). Data is a FILETIME timestamp of last execution. Entries cleared after ~7 days. Very reliable execution evidence."),
            tools: sv(&["Registry Explorer", "RegRipper", "Strata Tree"]),
        },
        super::ForensicArtifact {
            name: s("$MFT"),
            path: s("$MFT (root of NTFS volume)"),
            description: s("Master File Table contains a record for every file and directory on an NTFS volume with all metadata and timestamps."),
            forensic_value: s("Complete file system metadata including $STANDARD_INFORMATION and $FILE_NAME timestamps (4 timestamps each = 8 per file). Reveals timestomping by comparing SI vs FN timestamps."),
            interpretation: s("Each MFT record is 1024 bytes. Contains: $STANDARD_INFORMATION (user-modifiable timestamps), $FILE_NAME (OS-managed timestamps), $DATA (file content or run lists). Deleted files retain MFT records until overwritten. SI timestamps can be backdated (timestomping) but FN timestamps are harder to modify."),
            tools: sv(&["MFTECmd (Eric Zimmerman)", "analyzeMFT", "Autopsy", "Strata Tree"]),
        },
        super::ForensicArtifact {
            name: s("USN Journal"),
            path: s("$Extend\\$UsnJrnl:$J"),
            description: s("NTFS Update Sequence Number Journal records all file system changes (creation, deletion, rename, content change) with timestamps."),
            forensic_value: s("Near real-time log of all file system activity. Shows file creation, deletion, rename, and attribute changes with timestamps."),
            interpretation: s("Each entry contains: MFT reference, parent MFT reference, timestamp, reason flags, filename. Reason flags decode to: FILE_CREATE, FILE_DELETE, DATA_EXTEND, RENAME_NEW_NAME, etc. Journal is circular and overwrites old entries."),
            tools: sv(&["MFTECmd (Eric Zimmerman)", "ANJP (TZWorks)", "Strata Tree"]),
        },
        super::ForensicArtifact {
            name: s("Volume Shadow Copies"),
            path: s("\\\\?\\GLOBALROOT\\Device\\HarddiskVolumeShadowCopy#"),
            description: s("Volume Shadow Copies are point-in-time snapshots of a volume. Ransomware commonly deletes them (vssadmin delete shadows)."),
            forensic_value: s("Can recover deleted files and previous versions of modified files. Deletion of shadow copies via vssadmin is strong indicator of ransomware activity."),
            interpretation: s("Access via vssadmin list shadows or mklink to mount. Compare current filesystem to shadow copy to find deleted or modified files. VSS deletion logged in Event ID 7036 (VSS service state change)."),
            tools: sv(&["vssadmin", "ShadowExplorer", "Arsenal Image Mounter", "Strata Tree"]),
        },
        super::ForensicArtifact {
            name: s("PowerShell History"),
            path: s("C:\\Users\\<user>\\AppData\\Roaming\\Microsoft\\Windows\\PowerShell\\PSReadLine\\ConsoleHost_history.txt"),
            description: s("PSReadLine saves all PowerShell commands typed by the user to a plain text file. Available Win10+."),
            forensic_value: s("Complete record of PowerShell commands executed interactively. May contain encoded commands, credential usage, and lateral movement commands."),
            interpretation: s("Plain text file, one command per line. No timestamps (correlate with Prefetch/EVTX). Look for: Invoke-Expression, IEX, -enc, DownloadString, New-Object Net.WebClient, credential variables."),
            tools: sv(&["Any text editor", "grep/findstr", "Strata Tree"]),
        },
        super::ForensicArtifact {
            name: s("SRUM Database"),
            path: s("C:\\Windows\\System32\\sru\\SRUDB.dat"),
            description: s("System Resource Usage Monitor tracks 30-60 days of application resource usage including network bytes, CPU time, and battery."),
            forensic_value: s("Proves application execution with network usage data. Shows bytes sent/received per application per hour. Can identify data exfiltration by volume."),
            interpretation: s("ESE database with tables: NetworkUsage (bytes per app per interface per hour), ApplicationResourceUsage (CPU, memory), EnergyUsage. AppId maps to executable path. Timestamps in 1-hour windows."),
            tools: sv(&["SrumECmd (Eric Zimmerman)", "srum-dump", "Autopsy"]),
        },
        super::ForensicArtifact {
            name: s("Scheduled Tasks"),
            path: s("C:\\Windows\\System32\\Tasks\\*; HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Schedule\\TaskCache\\Tasks; HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Schedule\\TaskCache\\Tree"),
            description: s("Windows Task Scheduler stores task definitions as XML files and caches metadata in the registry."),
            forensic_value: s("Identifies persistence mechanisms. Task XML contains: command to execute, triggers, run conditions, author, creation date."),
            interpretation: s("XML files in Tasks folder contain full task definition. Registry TaskCache\\Tasks contains hashes and metadata. TaskCache\\Tree maps names to GUIDs. Security Event 4698 logs task creation. Event 4699 logs deletion."),
            tools: sv(&["Autoruns (Sysinternals)", "Registry Explorer", "Task Scheduler GUI"]),
        },
        super::ForensicArtifact {
            name: s("WMI Repository"),
            path: s("C:\\Windows\\System32\\wbem\\Repository\\OBJECTS.DATA"),
            description: s("WMI Repository stores persistent WMI subscriptions. Attackers use event subscriptions for fileless persistence."),
            forensic_value: s("Identifies WMI-based persistence (T1546.003). Event subscriptions can trigger command execution on system events without files on disk."),
            interpretation: s("Look for __EventFilter + __EventConsumer + __FilterToConsumerBinding triplets. CommandLineEventConsumer and ActiveScriptEventConsumer are commonly abused. PyWMIPersistenceFinder can parse the repository."),
            tools: sv(&["PyWMIPersistenceFinder", "WMI Explorer", "Autoruns"]),
        },
        super::ForensicArtifact {
            name: s("MUICache"),
            path: s("NTUSER.DAT\\Software\\Classes\\Local Settings\\Software\\Microsoft\\Windows\\Shell\\MuiCache"),
            description: s("MUICache records the display names of executed programs as read from their version information."),
            forensic_value: s("Proves program execution. Contains full path and friendly name from the PE version info."),
            interpretation: s("Values are full path to executable. Data is the friendly name string. No timestamps in the values themselves but registry key last write time is available."),
            tools: sv(&["Registry Explorer", "MUICacheView (NirSoft)", "RegRipper"]),
        },
        super::ForensicArtifact {
            name: s("Windows.edb"),
            path: s("C:\\ProgramData\\Microsoft\\Search\\Data\\Applications\\Windows\\Windows.edb"),
            description: s("Windows Search index database (ESE format) caches metadata and partial content of indexed files."),
            forensic_value: s("Can reveal file existence and content even after deletion. Contains file paths, dates, sizes, and sometimes partial file content."),
            interpretation: s("ESE database indexed by file path. Contains metadata for all indexed locations. May contain email content, document text, and file properties that survived deletion."),
            tools: sv(&["ESEDatabaseView (NirSoft)", "WinSearchDBAnalyzer", "libesedb"]),
        },
    ]
}
