use super::MitreTechnique;

fn s(v: &str) -> String {
    v.to_string()
}

fn sv(v: &[&str]) -> Vec<String> {
    v.iter().map(|s| s.to_string()).collect()
}

fn t(
    id: &str,
    name: &str,
    tactic: &str,
    description: &str,
    sub_techniques: &[&str],
    detection: &str,
    artifacts: &[&str],
) -> MitreTechnique {
    MitreTechnique {
        id: s(id),
        name: s(name),
        tactic: s(tactic),
        description: s(description),
        sub_techniques: sv(sub_techniques),
        detection: s(detection),
        artifacts: sv(artifacts),
    }
}

/// Returns the full MITRE ATT&CK technique knowledge base.
pub fn all_techniques() -> Vec<MitreTechnique> {
    vec![
        // =====================================================================
        // INITIAL ACCESS
        // =====================================================================
        t(
            "T1566",
            "Phishing",
            "Initial Access",
            "Adversaries send phishing messages to gain access to victim systems. These messages may contain malicious attachments or links designed to lure users into executing code or divulging credentials.",
            &["T1566.001", "T1566.002"],
            "Monitor email gateway logs for suspicious attachments and URLs. Inspect mail flow rules and quarantine events in Exchange or O365 audit logs.",
            &["Email gateway logs", "Exchange message tracking logs", "O365 unified audit log", "Outlook OST/PST files", "Web proxy logs"],
        ),
        t(
            "T1566.001",
            "Phishing: Spearphishing Attachment",
            "Initial Access",
            "Adversaries send spearphishing emails with malicious attachments such as Office documents with macros, PDFs with exploits, or executable files disguised as benign documents.",
            &[],
            "Monitor email logs for attachment types commonly abused (DOC/DOCX with macros, HTA, ISO, LNK). Look for child process spawning from Office applications in Sysmon Event ID 1.",
            &["Email gateway attachment logs", "Sysmon Event ID 1 (Process Create)", "NTFS $MFT for dropped files", "Prefetch for Office apps", "Recent file LNK artifacts"],
        ),
        t(
            "T1566.002",
            "Phishing: Spearphishing Link",
            "Initial Access",
            "Adversaries send spearphishing emails containing links to malicious websites that host exploit kits, credential harvesting pages, or drive-by downloads.",
            &[],
            "Inspect web proxy and DNS logs for newly registered or suspicious domains accessed shortly after email delivery. Correlate with email gateway URL click tracking.",
            &["Web proxy logs", "DNS query logs", "Browser history", "Email URL click tracking", "NTFS download artifacts (Zone.Identifier ADS)"],
        ),
        t(
            "T1190",
            "Exploit Public-Facing Application",
            "Initial Access",
            "Adversaries exploit vulnerabilities in internet-facing applications such as web servers, VPNs, or mail servers to gain initial access to a network.",
            &[],
            "Monitor web server access logs for anomalous requests, error spikes, or known exploit signatures. Review IDS/IPS alerts and WAF logs for exploit attempts.",
            &["Web server access/error logs", "IDS/IPS alerts", "WAF logs", "Application crash dumps", "Sysmon Event ID 3 (Network Connection)"],
        ),
        t(
            "T1133",
            "External Remote Services",
            "Initial Access",
            "Adversaries leverage external-facing remote services such as VPNs, Citrix, or RDP gateways to gain initial access using valid credentials.",
            &[],
            "Monitor authentication logs for VPN and remote access services. Look for logins from unusual geographic locations or outside business hours.",
            &["VPN authentication logs", "Windows Security Event ID 4624/4625", "RDP Gateway logs", "Firewall connection logs", "Azure AD sign-in logs"],
        ),
        t(
            "T1195",
            "Supply Chain Compromise",
            "Initial Access",
            "Adversaries manipulate products or delivery mechanisms prior to receipt by the end consumer to compromise data or systems, such as injecting malicious code into legitimate software updates.",
            &[],
            "Monitor software update mechanisms and verify code signing on installed software. Compare file hashes of installed binaries against known-good values from vendors.",
            &["Software installation logs", "Code signing certificates", "File hash baselines", "Package manager logs", "NTFS $MFT timestamps for modified binaries"],
        ),

        // =====================================================================
        // EXECUTION
        // =====================================================================
        t(
            "T1059",
            "Command and Scripting Interpreter",
            "Execution",
            "Adversaries abuse command and script interpreters to execute commands, scripts, or binaries. These interpreters provide powerful capabilities for interaction with the operating system.",
            &["T1059.001", "T1059.003", "T1059.005", "T1059.006", "T1059.007"],
            "Monitor process creation events (Sysmon Event ID 1) for interpreter launches. Correlate parent-child process relationships for anomalous script execution chains.",
            &["Sysmon Event ID 1 (Process Create)", "Windows Security Event ID 4688", "PowerShell logs", "Command-line audit logs", "Prefetch files"],
        ),
        t(
            "T1059.001",
            "Command and Scripting Interpreter: PowerShell",
            "Execution",
            "Adversaries use PowerShell commands and scripts for execution. PowerShell provides powerful access to the .NET framework and Windows API, making it a favored tool for post-exploitation.",
            &[],
            "Enable PowerShell Script Block Logging (Event ID 4104) and Module Logging. Monitor for encoded commands via -EncodedCommand or -Enc flags in process creation events.",
            &["PowerShell Event ID 4104 (Script Block Logging)", "PowerShell Event ID 4103 (Module Logging)", "Sysmon Event ID 1", "ConsoleHost_history.txt", "Prefetch for powershell.exe"],
        ),
        t(
            "T1059.003",
            "Command and Scripting Interpreter: Windows Command Shell",
            "Execution",
            "Adversaries use cmd.exe to execute commands and batch scripts. The Windows command shell is commonly used for executing downloaded payloads, reconnaissance commands, and lateral movement scripts.",
            &[],
            "Monitor for cmd.exe spawning from unusual parent processes such as Office applications or web browsers. Audit command-line arguments in Sysmon Event ID 1.",
            &["Sysmon Event ID 1 (Process Create)", "Windows Security Event ID 4688", "Prefetch for cmd.exe", "BAT/CMD script files on disk", "NTFS $MFT for script artifacts"],
        ),
        t(
            "T1059.005",
            "Command and Scripting Interpreter: Visual Basic",
            "Execution",
            "Adversaries use VBScript and VBA macros to execute malicious code. VBA macros in Office documents and standalone VBScript files are common initial execution vectors.",
            &[],
            "Monitor for cscript.exe or wscript.exe process creation, especially when spawned by Office applications. Enable AMSI logging for script content inspection.",
            &["Sysmon Event ID 1 (Process Create)", "AMSI ETW logs", "Prefetch for cscript.exe/wscript.exe", "Office recent documents", "VBS files on disk"],
        ),
        t(
            "T1059.006",
            "Command and Scripting Interpreter: Python",
            "Execution",
            "Adversaries use Python scripts for execution, often leveraging the language's extensive library ecosystem for reconnaissance, data exfiltration, and payload delivery.",
            &[],
            "Monitor for python.exe or python3.exe process creation from unusual directories or parent processes. Check for pip install commands that fetch malicious packages.",
            &["Sysmon Event ID 1 (Process Create)", "Prefetch for python.exe", "Python script files (.py) on disk", "pip install logs", "NTFS $MFT for Python artifacts"],
        ),
        t(
            "T1059.007",
            "Command and Scripting Interpreter: JavaScript",
            "Execution",
            "Adversaries use JavaScript for execution via Windows Script Host (wscript/cscript), Node.js, or browser-based exploitation. JS files can be double-clicked to execute on Windows by default.",
            &[],
            "Monitor for wscript.exe or cscript.exe executing .js files. Look for node.exe spawning from unexpected locations. Track JavaScript file creation in temp directories.",
            &["Sysmon Event ID 1 (Process Create)", "Prefetch for wscript.exe/cscript.exe", "JS/JSE files on disk", "NTFS Zone.Identifier ADS", "Browser download history"],
        ),

        // =====================================================================
        // PERSISTENCE
        // =====================================================================
        t(
            "T1547",
            "Boot or Logon Autostart Execution",
            "Persistence",
            "Adversaries configure settings to execute programs during system boot or user logon to maintain persistence. This abuses the normal OS startup process to survive reboots.",
            &["T1547.001", "T1547.004", "T1547.005"],
            "Monitor registry run key modifications (Sysmon Event ID 13). Baseline autostart locations and alert on changes to startup folders or registry values.",
            &["Registry Run/RunOnce keys", "Startup folder contents", "Sysmon Event ID 13 (Registry Value Set)", "Autoruns output", "NTUSER.DAT hive"],
        ),
        t(
            "T1547.001",
            "Boot or Logon Autostart Execution: Registry Run Keys / Startup Folder",
            "Persistence",
            "Adversaries add programs to registry Run keys or the Startup folder to execute on each user logon. This is one of the most common persistence mechanisms observed in the wild.",
            &[],
            "Monitor Sysmon Event ID 13 for value changes to HKLM/HKCU Run and RunOnce keys. Audit the Startup folder for new LNK files or executables.",
            &["HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run", "HKCU\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run", "Startup folder LNK files", "Sysmon Event ID 13", "NTUSER.DAT registry hive"],
        ),
        t(
            "T1547.004",
            "Boot or Logon Autostart Execution: Winlogon Helper DLL",
            "Persistence",
            "Adversaries abuse Winlogon helper DLL registry values (Shell, Userinit, Notify) to execute malicious DLLs during the Windows logon process.",
            &[],
            "Monitor changes to Winlogon registry keys including Shell, Userinit, and Notify values. Compare current values against known-good baselines.",
            &["HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon (Shell, Userinit, Notify)", "Sysmon Event ID 13", "SYSTEM registry hive", "Loaded DLL analysis"],
        ),
        t(
            "T1547.005",
            "Boot or Logon Autostart Execution: Security Support Provider",
            "Persistence",
            "Adversaries abuse Security Support Provider (SSP) DLLs by adding malicious DLLs to the LSA configuration. These DLLs are loaded by lsass.exe on boot and can capture plaintext credentials.",
            &[],
            "Monitor changes to HKLM\\SYSTEM\\CurrentControlSet\\Control\\Lsa\\Security Packages registry value. Alert on new DLLs loaded by lsass.exe.",
            &["HKLM\\SYSTEM\\CurrentControlSet\\Control\\Lsa (Security Packages)", "Sysmon Event ID 7 (Image Loaded) for lsass.exe", "SYSTEM registry hive", "DLLs in System32 directory"],
        ),
        t(
            "T1053",
            "Scheduled Task/Job",
            "Persistence",
            "Adversaries abuse task scheduling functionality to execute malicious code at system startup or on a recurring schedule for persistence or privilege escalation.",
            &["T1053.005"],
            "Monitor Windows Security Event ID 4698 (Scheduled Task Created) and Sysmon Event ID 1 for schtasks.exe usage. Review scheduled task XML definitions for suspicious actions.",
            &["Windows Security Event ID 4698/4702", "Sysmon Event ID 1 for schtasks.exe", "C:\\Windows\\System32\\Tasks\\ XML files", "Task Scheduler operational log", "Prefetch for schtasks.exe"],
        ),
        t(
            "T1053.005",
            "Scheduled Task/Job: Scheduled Task",
            "Persistence",
            "Adversaries create or modify Windows scheduled tasks to execute malicious payloads on a recurring basis or at system startup for persistence.",
            &[],
            "Monitor for schtasks.exe /create commands in process creation logs. Review the Task Scheduler operational log (Microsoft-Windows-TaskScheduler/Operational) for new task registration.",
            &["Windows Security Event ID 4698 (Task Created)", "Task Scheduler operational log", "C:\\Windows\\System32\\Tasks\\ XML files", "Sysmon Event ID 1 for schtasks.exe", "Prefetch for schtasks.exe"],
        ),
        t(
            "T1543",
            "Create or Modify System Process",
            "Persistence",
            "Adversaries create or modify system-level processes to repeatedly execute malicious payloads as part of persistence. This includes Windows services and Linux daemons.",
            &["T1543.003"],
            "Monitor for sc.exe or New-Service PowerShell commands. Review Windows Security Event ID 4697 (Service Installed) and System Event ID 7045.",
            &["Windows System Event ID 7045 (Service Installed)", "Windows Security Event ID 4697", "SYSTEM registry hive (Services key)", "Sysmon Event ID 1 for sc.exe", "Service binary file analysis"],
        ),
        t(
            "T1543.003",
            "Create or Modify System Process: Windows Service",
            "Persistence",
            "Adversaries install or modify Windows services to execute malicious payloads. Services provide SYSTEM-level persistence that survives reboots and runs independently of user logon.",
            &[],
            "Monitor System Event ID 7045 for new service installations. Alert on services with binaries in unusual paths (temp dirs, user profiles). Review service failure recovery actions.",
            &["Windows System Event ID 7045", "HKLM\\SYSTEM\\CurrentControlSet\\Services registry key", "Sysmon Event ID 13 for service registry changes", "Service binary files", "Prefetch for sc.exe"],
        ),
        t(
            "T1098",
            "Account Manipulation",
            "Persistence",
            "Adversaries manipulate accounts to maintain access to victim systems. This includes modifying credentials, adding SSH keys, modifying permissions, or changing group memberships.",
            &[],
            "Monitor Windows Security Event IDs 4738 (User Account Changed) and 4732 (Member Added to Security Group). Review Azure AD and O365 audit logs for role changes.",
            &["Windows Security Event ID 4738", "Windows Security Event ID 4732/4733", "Active Directory change logs", "Azure AD audit logs", "SAM registry hive"],
        ),
        t(
            "T1136",
            "Create Account",
            "Persistence",
            "Adversaries create accounts to maintain access. New local or domain accounts provide persistent access that does not depend on deploying additional tools.",
            &["T1136.001", "T1136.002"],
            "Monitor Windows Security Event ID 4720 (User Account Created). Alert on account creation outside of normal provisioning workflows or from unexpected source hosts.",
            &["Windows Security Event ID 4720", "SAM registry hive", "Active Directory replication logs", "Net user command history", "Sysmon Event ID 1 for net.exe"],
        ),
        t(
            "T1136.001",
            "Create Account: Local Account",
            "Persistence",
            "Adversaries create local accounts on compromised systems to establish persistent access. These accounts may be added to privileged groups such as Administrators.",
            &[],
            "Monitor Windows Security Event ID 4720 (User Account Created) on individual endpoints. Alert when new local accounts are added to the Administrators group (Event ID 4732).",
            &["Windows Security Event ID 4720", "Windows Security Event ID 4732", "SAM registry hive", "Sysmon Event ID 1 for net.exe / net1.exe", "Prefetch for net.exe"],
        ),
        t(
            "T1136.002",
            "Create Account: Domain Account",
            "Persistence",
            "Adversaries create domain accounts on Active Directory to establish persistent access across the enterprise. Domain accounts provide broad access to network resources.",
            &[],
            "Monitor domain controller Security Event ID 4720 for new domain account creation. Correlate with the source workstation and operator account for anomalies.",
            &["Domain Controller Security Event ID 4720", "Active Directory replication metadata", "NTDS.dit changes", "Sysmon Event ID 1 on DCs for dsadd/net user", "Azure AD provisioning logs"],
        ),

        // =====================================================================
        // PRIVILEGE ESCALATION
        // =====================================================================
        t(
            "T1055",
            "Process Injection",
            "Privilege Escalation",
            "Adversaries inject code into the address space of another process to evade defenses and potentially elevate privileges. Injected code runs in the context of the target process.",
            &["T1055.001", "T1055.003", "T1055.012"],
            "Monitor for processes that allocate remote memory or write to other process memory using Sysmon Event ID 8 (CreateRemoteThread) and Event ID 10 (ProcessAccess).",
            &["Sysmon Event ID 8 (CreateRemoteThread)", "Sysmon Event ID 10 (ProcessAccess)", "Sysmon Event ID 1 (unusual parent-child)", "Memory dumps of suspicious processes", "Loaded DLL analysis"],
        ),
        t(
            "T1055.001",
            "Process Injection: Dynamic-link Library Injection",
            "Privilege Escalation",
            "Adversaries inject DLLs into the address space of another running process using APIs like VirtualAllocEx, WriteProcessMemory, and CreateRemoteThread.",
            &[],
            "Monitor Sysmon Event ID 8 for CreateRemoteThread targeting processes that do not normally receive remote threads. Alert on DLLs loaded from unusual paths.",
            &["Sysmon Event ID 8 (CreateRemoteThread)", "Sysmon Event ID 7 (Image Loaded) for unusual DLLs", "Sysmon Event ID 10 (ProcessAccess with PROCESS_VM_WRITE)", "Volatility malfind plugin output", "Process memory dumps"],
        ),
        t(
            "T1055.003",
            "Process Injection: Thread Execution Hijacking",
            "Privilege Escalation",
            "Adversaries hijack existing threads in a remote process by suspending the thread, modifying its context to point to injected code, and resuming execution.",
            &[],
            "Monitor for SuspendThread/SetThreadContext/ResumeThread API call sequences via ETW. Look for Sysmon Event ID 10 with unusual access rights to thread handles.",
            &["Sysmon Event ID 10 (ProcessAccess)", "ETW thread creation/modification events", "Process memory dumps", "Volatility threads plugin output", "API call traces"],
        ),
        t(
            "T1055.012",
            "Process Injection: Process Hollowing",
            "Privilege Escalation",
            "Adversaries create a process in a suspended state, hollow out its memory, replace it with malicious code, and resume execution. The process appears legitimate externally.",
            &[],
            "Monitor for processes created in a suspended state (CREATE_SUSPENDED flag) followed by memory writes. Compare in-memory image to on-disk binary for discrepancies.",
            &["Sysmon Event ID 1 (suspended process creation)", "Sysmon Event ID 10 (ProcessAccess)", "Process memory vs on-disk image comparison", "Volatility malfind/procdump output", "Hollows Hunter scan results"],
        ),
        t(
            "T1078",
            "Valid Accounts",
            "Privilege Escalation",
            "Adversaries obtain and abuse credentials of existing accounts to gain initial access, persistence, privilege escalation, or defense evasion across systems.",
            &["T1078.001", "T1078.002", "T1078.003"],
            "Monitor for logon anomalies including impossible travel, concurrent sessions, and off-hours authentication. Correlate failed and successful logon attempts.",
            &["Windows Security Event ID 4624/4625", "Windows Security Event ID 4648 (Explicit Credentials)", "Azure AD sign-in logs", "VPN authentication logs", "Active Directory logon audit"],
        ),
        t(
            "T1078.001",
            "Valid Accounts: Default Accounts",
            "Privilege Escalation",
            "Adversaries use default accounts that come preconfigured on systems such as Guest, Administrator, or default service accounts with known or blank passwords.",
            &[],
            "Monitor for authentication using default account names such as Administrator, Guest, or vendor default accounts. Alert on first-time logon of dormant default accounts.",
            &["Windows Security Event ID 4624 (Logon Type filter)", "SAM registry hive (account status)", "Failed logon attempts on default accounts", "Account lockout events", "Azure AD risky sign-in logs"],
        ),
        t(
            "T1078.002",
            "Valid Accounts: Domain Accounts",
            "Privilege Escalation",
            "Adversaries use compromised domain credentials to access resources across the enterprise. Domain accounts enable broad lateral movement and access to sensitive data.",
            &[],
            "Monitor for domain account logons from unusual source hosts or at unusual times. Correlate with threat intelligence for known-compromised credential databases.",
            &["Domain Controller Security Event ID 4624/4768/4769", "Windows Security Event ID 4648", "Active Directory authentication logs", "NTDS.dit forensic analysis", "Kerberos ticket logs"],
        ),
        t(
            "T1078.003",
            "Valid Accounts: Local Accounts",
            "Privilege Escalation",
            "Adversaries use compromised local account credentials to log on to systems. Local accounts are particularly useful when domain credentials are unavailable.",
            &[],
            "Monitor Windows Security Event ID 4624 Logon Type 2 and 10 for local account usage. Alert on local account authentication on systems where the account was not provisioned.",
            &["Windows Security Event ID 4624/4625 (local logon types)", "SAM registry hive", "NTLM authentication logs", "Cached credentials (SECURITY hive)", "Sysmon Event ID 1 for runas.exe"],
        ),

        // =====================================================================
        // DEFENSE EVASION
        // =====================================================================
        t(
            "T1027",
            "Obfuscated Files or Information",
            "Defense Evasion",
            "Adversaries obfuscate payloads, scripts, or data to make detection and analysis more difficult. Techniques include encoding, encryption, packing, and string manipulation.",
            &["T1027.001", "T1027.010"],
            "Use file entropy analysis to detect packed or encrypted binaries. Monitor for Base64-encoded command-line arguments and scripts with excessive string manipulation.",
            &["File entropy analysis results", "Sysmon Event ID 1 (encoded command lines)", "AMSI logs for deobfuscated content", "Static analysis of suspicious binaries", "Sandbox detonation reports"],
        ),
        t(
            "T1027.001",
            "Obfuscated Files or Information: Binary Padding",
            "Defense Evasion",
            "Adversaries pad binaries with junk data to alter file hashes and evade hash-based detection. This can also inflate file size to bypass sandbox analysis thresholds.",
            &[],
            "Compare file sizes of suspected binaries against known-good versions. Detect appended null bytes or repeating patterns at the end of PE files through entropy analysis.",
            &["PE file section analysis", "File entropy per-section analysis", "Hash comparison against known-good baselines", "File size anomaly detection", "YARA rule scan results"],
        ),
        t(
            "T1027.010",
            "Obfuscated Files or Information: Command Obfuscation",
            "Defense Evasion",
            "Adversaries obfuscate commands using techniques like character insertion, string concatenation, environment variable substitution, and encoding to evade command-line logging detection.",
            &[],
            "Enable enhanced command-line logging and apply deobfuscation rules. Monitor for excessive use of carets, percent signs, and environment variable expansion in cmd.exe commands.",
            &["Sysmon Event ID 1 (command-line arguments)", "PowerShell Script Block Logging (deobfuscated)", "AMSI ETW logs", "Windows Security Event ID 4688 (Process Creation with command line)", "Bash history files"],
        ),
        t(
            "T1140",
            "Deobfuscate/Decode Files or Information",
            "Defense Evasion",
            "Adversaries deobfuscate or decode data that was previously encoded or encrypted to reveal payloads for execution. This often uses built-in utilities like certutil or PowerShell.",
            &[],
            "Monitor for certutil -decode, PowerShell [Convert]::FromBase64String, or other decoding utility usage. Alert on new files created immediately after decoding operations.",
            &["Sysmon Event ID 1 for certutil.exe / powershell.exe", "Sysmon Event ID 11 (File Created) after decode operations", "Prefetch for certutil.exe", "PowerShell Script Block Logging", "NTFS $MFT for decoded file timestamps"],
        ),
        t(
            "T1070",
            "Indicator Removal",
            "Defense Evasion",
            "Adversaries delete or modify artifacts on a host system to remove evidence of their presence. This includes clearing logs, deleting files, and modifying timestamps.",
            &["T1070.001", "T1070.004", "T1070.006"],
            "Monitor for log clearing events (Security Event ID 1102) and bulk file deletions. Enable audit policy for object deletion and file system changes.",
            &["Windows Security Event ID 1102 (Audit Log Cleared)", "Windows System Event ID 104 (Log Cleared)", "Sysmon Event ID 23 (File Delete Archived)", "USN Journal for deletion records", "NTFS $MFT for deleted file entries"],
        ),
        t(
            "T1070.001",
            "Indicator Removal: Clear Windows Event Logs",
            "Defense Evasion",
            "Adversaries clear Windows Event Logs to remove evidence of intrusion activities. This can be done via wevtutil, PowerShell Clear-EventLog, or direct manipulation of .evtx files.",
            &[],
            "Monitor Security Event ID 1102 (The audit log was cleared) and System Event ID 104. Alert on wevtutil cl commands in process creation logs.",
            &["Windows Security Event ID 1102", "Windows System Event ID 104", "Sysmon Event ID 1 for wevtutil.exe", "Event log file $MFT timestamps", "Prefetch for wevtutil.exe"],
        ),
        t(
            "T1070.004",
            "Indicator Removal: File Deletion",
            "Defense Evasion",
            "Adversaries delete files to remove indicators of compromise such as malware binaries, scripts, and tool output. This includes secure deletion and overwriting techniques.",
            &[],
            "Monitor Sysmon Event ID 23 (File Delete Archived) and Event ID 26 (File Delete Logged). Review USN Journal for deletion records of suspicious files.",
            &["Sysmon Event ID 23/26 (File Delete)", "NTFS USN Journal ($UsnJrnl)", "NTFS $MFT entries for deleted files", "$Recycle.Bin analysis", "Prefetch for sdelete.exe or cipher.exe"],
        ),
        t(
            "T1070.006",
            "Indicator Removal: Timestomp",
            "Defense Evasion",
            "Adversaries modify file timestamps (MACE values) to make malicious files appear benign or blend in with legitimate system files, complicating forensic timeline analysis.",
            &[],
            "Compare $STANDARD_INFORMATION timestamps with $FILE_NAME timestamps in NTFS $MFT. Detect discrepancies where SI timestamps are older than FN timestamps.",
            &["NTFS $MFT $STANDARD_INFORMATION vs $FILE_NAME timestamp comparison", "USN Journal entries (timestamp vs creation order)", "Sysmon Event ID 2 (File Creation Time Changed)", "NTFS $LogFile analysis", "File system timeline analysis"],
        ),
        t(
            "T1036",
            "Masquerading",
            "Defense Evasion",
            "Adversaries manipulate features of their artifacts to make them appear legitimate. This includes renaming utilities, matching file names of system files, or using valid code signing.",
            &["T1036.005"],
            "Compare running process names and paths against known-good system binary locations. Flag executables with system file names running from non-standard directories.",
            &["Sysmon Event ID 1 (process path vs name mismatch)", "Code signing verification results", "File version information analysis", "PE header compilation timestamp", "Known-good hash baseline comparison"],
        ),
        t(
            "T1036.005",
            "Masquerading: Match Legitimate Name or Location",
            "Defense Evasion",
            "Adversaries rename malicious executables to match names of legitimate system utilities (e.g., svchost.exe, explorer.exe) and place them in expected directories.",
            &[],
            "Verify that processes with known system binary names are running from their expected paths (e.g., svchost.exe should only run from System32). Alert on path mismatches.",
            &["Sysmon Event ID 1 (Image path verification)", "PE Authenticode signature verification", "File hash comparison against known-good baselines", "NTFS $MFT file path analysis", "Loaded module path verification"],
        ),
        t(
            "T1218",
            "System Binary Proxy Execution",
            "Defense Evasion",
            "Adversaries abuse signed system binaries (LOLBins) to proxy execution of malicious payloads, bypassing application whitelisting and code signing enforcement.",
            &["T1218.005", "T1218.010", "T1218.011"],
            "Monitor for signed Microsoft binaries executing unusual child processes, loading DLLs from non-standard locations, or making outbound network connections.",
            &["Sysmon Event ID 1 (LOLBin process creation)", "Sysmon Event ID 7 (DLL load by LOLBins)", "Sysmon Event ID 3 (network connections by LOLBins)", "Application whitelisting logs", "Prefetch for LOLBin executables"],
        ),
        t(
            "T1218.005",
            "System Binary Proxy Execution: Mshta",
            "Defense Evasion",
            "Adversaries abuse mshta.exe to proxy execution of malicious HTA files and scripts. Mshta can execute inline VBScript/JScript, bypass application whitelisting, and reach the internet.",
            &[],
            "Monitor for mshta.exe process creation, especially when launched with URL arguments or inline script content. Alert on mshta.exe making network connections.",
            &["Sysmon Event ID 1 for mshta.exe", "Sysmon Event ID 3 (network connections from mshta.exe)", "Prefetch for mshta.exe", "HTA files on disk", "Proxy logs for HTA file downloads"],
        ),
        t(
            "T1218.010",
            "System Binary Proxy Execution: Regsvr32",
            "Defense Evasion",
            "Adversaries abuse regsvr32.exe to proxy execution of malicious DLLs or scriptlets (SCT files). Regsvr32 can load COM scriptlets from remote URLs bypassing whitelisting.",
            &[],
            "Monitor for regsvr32.exe executing with /s /n /u /i flags or loading scriptlets from remote URLs. Alert on regsvr32.exe spawning child processes or making network connections.",
            &["Sysmon Event ID 1 for regsvr32.exe", "Sysmon Event ID 3 (network connections from regsvr32.exe)", "Sysmon Event ID 7 (DLLs loaded by regsvr32.exe)", "Prefetch for regsvr32.exe", "Proxy logs for SCT file downloads"],
        ),
        t(
            "T1218.011",
            "System Binary Proxy Execution: Rundll32",
            "Defense Evasion",
            "Adversaries abuse rundll32.exe to proxy execution of malicious DLLs. Rundll32 can load DLLs from arbitrary paths and execute exported functions.",
            &[],
            "Monitor rundll32.exe command-line arguments for DLLs loaded from temp directories, user profiles, or UNC paths. Alert on rundll32 spawning unexpected child processes.",
            &["Sysmon Event ID 1 for rundll32.exe (with arguments)", "Sysmon Event ID 7 (DLLs loaded by rundll32.exe)", "Sysmon Event ID 3 (network connections from rundll32.exe)", "Prefetch for rundll32.exe", "DLL file analysis from referenced paths"],
        ),
        t(
            "T1112",
            "Modify Registry",
            "Defense Evasion",
            "Adversaries modify the Windows registry to hide configuration data, remove evidence, disable security features, or establish persistence mechanisms.",
            &[],
            "Monitor Sysmon Event ID 13 (Registry Value Set) and Event ID 12 (Registry Object Added/Deleted). Alert on modifications to security-related registry keys.",
            &["Sysmon Event ID 12/13/14 (Registry events)", "Registry hive files (SYSTEM, SOFTWARE, NTUSER.DAT, SAM)", "Windows Security Event ID 4657 (Registry Value Modified)", "Registry transaction logs (.LOG files)", "RegBack snapshots"],
        ),

        // =====================================================================
        // CREDENTIAL ACCESS
        // =====================================================================
        t(
            "T1003",
            "OS Credential Dumping",
            "Credential Access",
            "Adversaries dump credentials from the operating system to obtain account login information. This enables further lateral movement and privilege escalation within the network.",
            &["T1003.001", "T1003.002", "T1003.003", "T1003.004", "T1003.006"],
            "Monitor for processes accessing LSASS memory (Sysmon Event ID 10). Alert on known credential dumping tool signatures and suspicious process access patterns.",
            &["Sysmon Event ID 10 (ProcessAccess targeting lsass.exe)", "Sysmon Event ID 1 for known dump tools", "Windows Security Event ID 4656 (SAM handle)", "LSASS memory dumps on disk", "Prefetch for credential dump tools"],
        ),
        t(
            "T1003.001",
            "OS Credential Dumping: LSASS Memory",
            "Credential Access",
            "Adversaries access LSASS process memory to extract plaintext passwords, NTLM hashes, and Kerberos tickets. Common tools include Mimikatz, ProcDump, and comsvcs.dll MiniDump.",
            &[],
            "Monitor Sysmon Event ID 10 for processes accessing lsass.exe with PROCESS_VM_READ. Enable Credential Guard and LSA RunAsPPL to mitigate.",
            &["Sysmon Event ID 10 (lsass.exe ProcessAccess)", "Sysmon Event ID 1 for procdump.exe, mimikatz.exe", "Sysmon Event ID 11 for .dmp files", "Windows Defender Credential Guard logs", "WER crash dumps for lsass"],
        ),
        t(
            "T1003.002",
            "OS Credential Dumping: Security Account Manager",
            "Credential Access",
            "Adversaries extract credential hashes from the SAM database, which stores local account password hashes. This is done via registry save, Volume Shadow Copy, or direct file access.",
            &[],
            "Monitor for reg.exe save commands targeting the SAM, SYSTEM, or SECURITY hives. Alert on vssadmin or wmic shadowcopy commands used to access locked registry files.",
            &["Sysmon Event ID 1 for reg.exe save / vssadmin.exe", "Windows Security Event ID 4656/4663 (SAM access)", "Registry hive files (SAM, SYSTEM)", "Volume Shadow Copy creation logs", "Prefetch for reg.exe / vssadmin.exe"],
        ),
        t(
            "T1003.003",
            "OS Credential Dumping: NTDS",
            "Credential Access",
            "Adversaries access the NTDS.dit Active Directory database to extract domain password hashes. This is done via ntdsutil, Volume Shadow Copy, or DCSync techniques.",
            &[],
            "Monitor domain controllers for ntdsutil.exe or vssadmin.exe usage. Alert on replication requests from non-DC sources (Event ID 4662 with DS-Replication extended rights).",
            &["Sysmon Event ID 1 for ntdsutil.exe on DCs", "Windows Security Event ID 4662 (Directory Service Access)", "Volume Shadow Copy creation on DCs", "NTDS.dit file access logs", "Prefetch for ntdsutil.exe"],
        ),
        t(
            "T1003.004",
            "OS Credential Dumping: LSA Secrets",
            "Credential Access",
            "Adversaries extract LSA Secrets from the SECURITY registry hive to obtain credentials including service account passwords, auto-logon passwords, and cached domain credentials.",
            &[],
            "Monitor for reg.exe save on the SECURITY hive. Alert on tools that parse LSA secrets such as secretsdump or Mimikatz lsadump::secrets.",
            &["Sysmon Event ID 1 for reg.exe save SECURITY", "Windows Security Event ID 4656 (SECURITY hive access)", "SECURITY registry hive", "Sysmon Event ID 10 for lsass access", "Prefetch for secretsdump utilities"],
        ),
        t(
            "T1003.006",
            "OS Credential Dumping: DCSync",
            "Credential Access",
            "Adversaries use domain replication protocol to request password hashes from domain controllers. DCSync abuses the DS-Replication-Get-Changes-All extended right without direct DC access.",
            &[],
            "Monitor Windows Security Event ID 4662 for DS-Replication-Get-Changes and DS-Replication-Get-Changes-All from non-DC sources. Alert on unexpected replication partners.",
            &["Windows Security Event ID 4662 (DS-Replication rights)", "Domain Controller replication logs", "Network traffic analysis (DRSUAPI RPC)", "Active Directory object access audit", "Sysmon Event ID 3 (network to DC on RPC ports)"],
        ),
        t(
            "T1555",
            "Credentials from Password Stores",
            "Credential Access",
            "Adversaries search password stores such as browser credential managers, Windows Credential Manager, and third-party vaults to obtain user credentials.",
            &["T1555.003"],
            "Monitor for processes accessing credential store files or APIs. Alert on unexpected access to browser profile directories and Credential Manager vaults.",
            &["Sysmon Event ID 1 for credential access tools", "File access to browser credential databases", "Windows Credential Manager vault files", "DPAPI master key access", "Sysmon Event ID 11 for copied credential files"],
        ),
        t(
            "T1555.003",
            "Credentials from Password Stores: Credentials from Web Browsers",
            "Credential Access",
            "Adversaries extract saved credentials from web browser password stores. Browsers store credentials in SQLite databases or encrypted files that can be decrypted with local DPAPI keys.",
            &[],
            "Monitor for processes accessing browser credential databases (Login Data, logins.json). Alert on non-browser processes reading these files.",
            &["File access to Chrome Login Data / Firefox logins.json", "DPAPI master key access (Event ID 4692)", "Sysmon Event ID 1 for credential extraction tools", "Browser profile directory access", "NTFS $MFT for copied browser files"],
        ),
        t(
            "T1558",
            "Steal or Forge Kerberos Tickets",
            "Credential Access",
            "Adversaries steal or forge Kerberos tickets to move laterally or escalate privileges. Techniques include Golden Ticket, Silver Ticket, and Kerberoasting attacks.",
            &["T1558.003"],
            "Monitor for unusual Kerberos ticket requests, especially TGS requests for service accounts. Alert on anomalous Kerberos authentication patterns and encryption downgrade attempts.",
            &["Windows Security Event ID 4768 (TGT Request)", "Windows Security Event ID 4769 (TGS Request)", "Kerberos ticket encryption type analysis", "Domain Controller authentication logs", "Network traffic for Kerberos protocol anomalies"],
        ),
        t(
            "T1558.003",
            "Steal or Forge Kerberos Tickets: Kerberoasting",
            "Credential Access",
            "Adversaries request Kerberos TGS tickets for service accounts and crack them offline to obtain plaintext credentials. Service accounts often have weak passwords and elevated privileges.",
            &[],
            "Monitor for high volumes of TGS requests (Event ID 4769) for service accounts from a single source, especially using RC4 encryption (type 0x17) instead of AES.",
            &["Windows Security Event ID 4769 (TGS requests with RC4)", "Domain Controller Kerberos logs", "Service account SPN enumeration (Event ID 4769 patterns)", "Network capture of TGS-REP packets", "Active Directory service account audit"],
        ),

        // =====================================================================
        // DISCOVERY
        // =====================================================================
        t(
            "T1057",
            "Process Discovery",
            "Discovery",
            "Adversaries enumerate running processes to gain information about software and services on a system. This helps identify security tools, running applications, and potential injection targets.",
            &[],
            "Monitor for tasklist.exe, Get-Process, or wmic process invocations from unusual parent processes. Baseline normal process enumeration activity per endpoint.",
            &["Sysmon Event ID 1 for tasklist.exe / wmic.exe", "PowerShell Script Block Logging for Get-Process", "Prefetch for tasklist.exe", "Windows Security Event ID 4688", "WMI activity logs"],
        ),
        t(
            "T1082",
            "System Information Discovery",
            "Discovery",
            "Adversaries collect system information including OS version, architecture, hostname, and hardware details to tailor subsequent attack stages to the target environment.",
            &[],
            "Monitor for systeminfo.exe, wmic os, or hostname commands executed from non-administrative contexts. Correlate with other discovery commands in the same session.",
            &["Sysmon Event ID 1 for systeminfo.exe / hostname.exe", "PowerShell Script Block Logging for Get-ComputerInfo", "Prefetch for systeminfo.exe", "WMI query logs", "Windows Security Event ID 4688"],
        ),
        t(
            "T1016",
            "System Network Configuration Discovery",
            "Discovery",
            "Adversaries enumerate network configuration details including IP addresses, DNS servers, gateways, and routing tables to understand the network topology.",
            &[],
            "Monitor for ipconfig, route print, arp, and netsh commands. Alert on multiple network discovery commands executed in rapid succession from the same process.",
            &["Sysmon Event ID 1 for ipconfig.exe / route.exe / arp.exe", "PowerShell logs for Get-NetIPAddress / Get-NetRoute", "Prefetch for network utility executables", "Command-line audit logs", "Windows Security Event ID 4688"],
        ),
        t(
            "T1033",
            "System Owner/User Discovery",
            "Discovery",
            "Adversaries enumerate the current user, logged-on users, and user accounts to identify the security context and determine available privileges on the compromised system.",
            &[],
            "Monitor for whoami.exe, quser.exe, and query user commands. Alert on whoami /priv or whoami /groups from non-administrative scripts.",
            &["Sysmon Event ID 1 for whoami.exe / quser.exe", "PowerShell logs for [Environment]::UserName", "Prefetch for whoami.exe", "Windows Security Event ID 4688", "Command-line audit logs"],
        ),
        t(
            "T1069",
            "Permission Groups Discovery",
            "Discovery",
            "Adversaries enumerate local and domain groups to identify group memberships and privileges. This information helps determine which accounts have elevated access.",
            &["T1069.001", "T1069.002"],
            "Monitor for net localgroup, net group /domain, and Get-ADGroup commands. Alert on broad group enumeration from non-administrative contexts.",
            &["Sysmon Event ID 1 for net.exe / net1.exe", "PowerShell Script Block Logging for Get-ADGroupMember", "Prefetch for net.exe", "Windows Security Event ID 4688", "Active Directory LDAP query logs"],
        ),
        t(
            "T1069.001",
            "Permission Groups Discovery: Local Groups",
            "Discovery",
            "Adversaries enumerate local groups such as Administrators and Remote Desktop Users to identify accounts with elevated local privileges.",
            &[],
            "Monitor for net localgroup Administrators and similar commands. Alert on enumeration of privileged local groups from non-administrative user sessions.",
            &["Sysmon Event ID 1 for net.exe localgroup", "PowerShell logs for Get-LocalGroupMember", "Prefetch for net.exe", "Windows Security Event ID 4688", "SAM registry hive (group membership)"],
        ),
        t(
            "T1069.002",
            "Permission Groups Discovery: Domain Groups",
            "Discovery",
            "Adversaries enumerate domain groups such as Domain Admins and Enterprise Admins to identify high-value accounts for targeting in privilege escalation or lateral movement.",
            &[],
            "Monitor for net group /domain commands and LDAP queries targeting privileged group objects. Alert on broad domain group enumeration from workstations.",
            &["Sysmon Event ID 1 for net.exe group /domain", "LDAP query logs on domain controllers", "PowerShell logs for Get-ADGroup", "Windows Security Event ID 4688", "Active Directory access audit logs"],
        ),
        t(
            "T1087",
            "Account Discovery",
            "Discovery",
            "Adversaries enumerate accounts on local systems and within the domain to identify accounts that can be targeted for credential theft or lateral movement.",
            &["T1087.001", "T1087.002"],
            "Monitor for net user, wmic useraccount, and Get-ADUser commands. Alert on comprehensive account enumeration from non-administrative endpoints.",
            &["Sysmon Event ID 1 for net.exe user", "PowerShell Script Block Logging for Get-ADUser / Get-LocalUser", "Prefetch for net.exe", "Windows Security Event ID 4688", "LDAP query logs"],
        ),
        t(
            "T1087.001",
            "Account Discovery: Local Account",
            "Discovery",
            "Adversaries enumerate local user accounts to identify accounts available on the compromised system, including service accounts and administrator accounts.",
            &[],
            "Monitor for net user and wmic useraccount commands on local systems. Alert on enumeration from unusual parent processes or scripts.",
            &["Sysmon Event ID 1 for net.exe user (without /domain)", "PowerShell logs for Get-LocalUser", "Prefetch for net.exe", "SAM registry hive", "Windows Security Event ID 4688"],
        ),
        t(
            "T1087.002",
            "Account Discovery: Domain Account",
            "Discovery",
            "Adversaries enumerate domain user accounts to identify targets for credential theft, privilege escalation, or lateral movement across the enterprise network.",
            &[],
            "Monitor for net user /domain and LDAP enumeration queries. Alert on broad user attribute queries from workstations, especially targeting privileged accounts.",
            &["Sysmon Event ID 1 for net.exe user /domain", "LDAP query logs on domain controllers", "PowerShell logs for Get-ADUser", "Windows Security Event ID 4688", "Active Directory access audit logs"],
        ),

        // =====================================================================
        // LATERAL MOVEMENT
        // =====================================================================
        t(
            "T1021",
            "Remote Services",
            "Lateral Movement",
            "Adversaries use valid accounts to log into remote services to move laterally within a network. Remote services provide authenticated access to other networked systems.",
            &["T1021.001", "T1021.002", "T1021.003", "T1021.006"],
            "Monitor for remote logon events (Event ID 4624 Logon Type 3, 10) and correlate with source/destination pairs. Alert on unusual lateral movement patterns.",
            &["Windows Security Event ID 4624 (Logon Type 3/10)", "Windows Security Event ID 4648 (Explicit Credentials)", "Sysmon Event ID 3 (Network Connections)", "Firewall connection logs", "Remote service authentication logs"],
        ),
        t(
            "T1021.001",
            "Remote Services: Remote Desktop Protocol",
            "Lateral Movement",
            "Adversaries use RDP to move laterally by connecting to remote systems with compromised credentials. RDP provides full interactive desktop access to the target system.",
            &[],
            "Monitor for Windows Security Event ID 4624 Logon Type 10 (RemoteInteractive). Review TerminalServices-RemoteConnectionManager logs for incoming RDP connection attempts.",
            &["Windows Security Event ID 4624 Logon Type 10", "TerminalServices-LocalSessionManager Event ID 21/25", "TerminalServices-RemoteConnectionManager Event ID 1149", "RDP Bitmap Cache files", "NTUSER.DAT (RDP connection MRU)"],
        ),
        t(
            "T1021.002",
            "Remote Services: SMB/Windows Admin Shares",
            "Lateral Movement",
            "Adversaries use SMB and Windows administrative shares (C$, ADMIN$, IPC$) to move laterally by copying files and executing commands on remote systems.",
            &[],
            "Monitor for Windows Security Event ID 5140/5145 (Network Share Access) for admin shares. Alert on unusual hosts accessing ADMIN$ or C$ shares.",
            &["Windows Security Event ID 5140/5145 (Share Access)", "Windows Security Event ID 4624 Logon Type 3", "Sysmon Event ID 3 (SMB port 445 connections)", "Sysmon Event ID 11 (files written via shares)", "SMB session logs"],
        ),
        t(
            "T1021.003",
            "Remote Services: Distributed Component Object Model",
            "Lateral Movement",
            "Adversaries use DCOM to execute commands on remote systems. DCOM provides a mechanism for inter-process communication that can be abused for lateral movement.",
            &[],
            "Monitor for DCOM-related process creation, especially instances of mmc.exe, excel.exe, or other COM servers spawning unusual child processes remotely.",
            &["Sysmon Event ID 1 (child processes from COM servers)", "Windows Security Event ID 4624 Logon Type 3", "DCOM LaunchPermission registry keys", "Sysmon Event ID 3 (DCOM RPC connections)", "Distributed COM event logs"],
        ),
        t(
            "T1021.006",
            "Remote Services: Windows Remote Management",
            "Lateral Movement",
            "Adversaries use WinRM (Windows Remote Management) to execute commands on remote systems via the WS-Management protocol. WinRM is the foundation of PowerShell remoting.",
            &[],
            "Monitor for WinRM connection events in Microsoft-Windows-WinRM/Operational log. Alert on wsmprovhost.exe process creation on destination systems.",
            &["Microsoft-Windows-WinRM/Operational Event ID 6/91", "Sysmon Event ID 1 for wsmprovhost.exe", "Windows Security Event ID 4624 Logon Type 3", "PowerShell remoting logs (Event ID 4103/4104)", "Sysmon Event ID 3 (WinRM port 5985/5986)"],
        ),
        t(
            "T1570",
            "Lateral Tool Transfer",
            "Lateral Movement",
            "Adversaries transfer tools and payloads between systems within a compromised network using SMB shares, RDP clipboard, or other internal protocols to avoid internet-facing defenses.",
            &[],
            "Monitor for file writes to SMB shares (Sysmon Event ID 11) and large file transfers between internal hosts. Alert on executable files written to admin shares.",
            &["Sysmon Event ID 11 (File Created on shares)", "Windows Security Event ID 5145 (Share object access)", "Sysmon Event ID 3 (internal SMB/RDP connections)", "NTFS $MFT for new files on shares", "Network traffic analysis for internal transfers"],
        ),

        // =====================================================================
        // COLLECTION
        // =====================================================================
        t(
            "T1005",
            "Data from Local System",
            "Collection",
            "Adversaries collect data from the local file system including documents, databases, source code, and configuration files before exfiltration.",
            &[],
            "Monitor for unusual file access patterns, especially bulk reads of sensitive file types. Alert on archive creation in staging directories.",
            &["Sysmon Event ID 11 (File Created in staging dirs)", "NTFS $MFT for bulk file access timestamps", "Windows Security Event ID 4663 (Object Access)", "File access audit logs", "USN Journal for mass file reads"],
        ),
        t(
            "T1039",
            "Data from Network Shared Drive",
            "Collection",
            "Adversaries search and collect data from network shared drives and mapped drives accessible from compromised systems.",
            &[],
            "Monitor for bulk access to file shares (Event ID 5145) from single hosts. Alert on unusual volumes of file reads from network shares outside normal business patterns.",
            &["Windows Security Event ID 5140/5145 (Share Access)", "Sysmon Event ID 3 (SMB connections)", "File server access logs", "DFS namespace access logs", "Network traffic volume analysis"],
        ),
        t(
            "T1560",
            "Archive Collected Data",
            "Collection",
            "Adversaries compress and encrypt collected data before exfiltration to reduce data volume and avoid content inspection by security tools.",
            &["T1560.001"],
            "Monitor for archive utility execution (7z, WinRAR, tar) with large input directories. Alert on password-protected archive creation in unusual locations.",
            &["Sysmon Event ID 1 for 7z.exe / rar.exe / tar.exe", "Sysmon Event ID 11 for new archive files", "Prefetch for archive utilities", "NTFS $MFT for archive file creation", "Command-line arguments showing password-protected archives"],
        ),
        t(
            "T1560.001",
            "Archive Collected Data: Archive via Utility",
            "Collection",
            "Adversaries use utilities such as 7-Zip, WinRAR, or zip to compress collected data before exfiltration. These utilities may be brought by the adversary or already present on the system.",
            &[],
            "Monitor for 7z.exe, rar.exe, or zip.exe process creation with command-line arguments referencing sensitive directories. Alert on archive creation in temp or staging directories.",
            &["Sysmon Event ID 1 for archive utilities", "Prefetch for 7z.exe / rar.exe / zip.exe", "Sysmon Event ID 11 for .zip/.rar/.7z files", "Command-line audit logs", "NTFS $MFT for archive timestamps"],
        ),

        // =====================================================================
        // EXFILTRATION
        // =====================================================================
        t(
            "T1041",
            "Exfiltration Over C2 Channel",
            "Exfiltration",
            "Adversaries exfiltrate stolen data over the existing command-and-control channel rather than opening a new connection. This blends exfiltration with normal C2 traffic.",
            &[],
            "Monitor for large outbound data transfers over C2 protocols. Analyze network flow data for sessions with unusually high upload-to-download ratios.",
            &["Network flow data (NetFlow/IPFIX)", "Proxy logs (upload volume per session)", "Sysmon Event ID 3 (outbound connections)", "IDS/IPS alerts for data exfiltration signatures", "Firewall connection logs (bytes sent)"],
        ),
        t(
            "T1048",
            "Exfiltration Over Alternative Protocol",
            "Exfiltration",
            "Adversaries exfiltrate data using a different protocol than the C2 channel, such as DNS tunneling, ICMP, SMTP, or FTP, to avoid detection on the primary communication path.",
            &[],
            "Monitor for unusual outbound protocol usage, especially DNS queries with high entropy, ICMP packets with payloads, or unexpected FTP/SMTP connections from endpoints.",
            &["DNS query logs (high entropy subdomain detection)", "Network flow data for unusual protocols", "Firewall logs for non-standard outbound ports", "Sysmon Event ID 3 (unexpected protocol usage)", "IDS alerts for DNS tunneling / ICMP exfiltration"],
        ),
        t(
            "T1567",
            "Exfiltration Over Web Service",
            "Exfiltration",
            "Adversaries exfiltrate data to legitimate cloud storage or web services such as Google Drive, Dropbox, Mega, or Pastebin to blend with normal traffic.",
            &[],
            "Monitor proxy logs for uploads to cloud storage services. Alert on large data transfers to file-sharing domains from endpoints that do not normally use these services.",
            &["Web proxy logs (uploads to cloud storage)", "DNS query logs for cloud storage domains", "Sysmon Event ID 3 (connections to cloud services)", "DLP alerts", "Browser history for cloud storage access"],
        ),

        // =====================================================================
        // IMPACT
        // =====================================================================
        t(
            "T1486",
            "Data Encrypted for Impact",
            "Impact",
            "Adversaries encrypt data on target systems to interrupt availability and hold organizations ransom. Ransomware typically encrypts user files and demands cryptocurrency payment for decryption keys.",
            &[],
            "Monitor for mass file rename operations with known ransomware extensions. Alert on high-frequency file modification events and volume shadow copy deletion.",
            &["Sysmon Event ID 11 (mass file creation with new extensions)", "Sysmon Event ID 23 (file deletion of originals)", "VSS deletion events (vssadmin/wmic)", "NTFS USN Journal (mass rename/modify)", "Ransom note file creation (Sysmon Event ID 11)"],
        ),
        t(
            "T1490",
            "Inhibit System Recovery",
            "Impact",
            "Adversaries delete or disable system recovery features including volume shadow copies, backup catalogs, and Windows Recovery Environment to prevent victims from restoring encrypted data.",
            &[],
            "Monitor for vssadmin delete shadows, wmic shadowcopy delete, and bcdedit /set recoveryenabled no commands. Alert on deletion of backup catalog files.",
            &["Sysmon Event ID 1 for vssadmin.exe / wmic.exe / bcdedit.exe", "Windows System Event ID 7036 (VSS service state)", "Prefetch for vssadmin.exe / bcdedit.exe", "Backup application logs", "BCD store modification logs"],
        ),

        // =====================================================================
        // COMMAND AND CONTROL
        // =====================================================================
        t(
            "T1071",
            "Application Layer Protocol",
            "Command and Control",
            "Adversaries communicate with compromised systems using application layer protocols such as HTTP, HTTPS, and DNS to blend C2 traffic with normal network communications.",
            &["T1071.001"],
            "Monitor for beaconing patterns in HTTP/HTTPS traffic with regular intervals. Analyze DNS queries for unusual patterns, long domain names, or high query frequency to suspicious domains.",
            &["Web proxy logs (beaconing detection)", "DNS query logs (DGA and tunneling detection)", "Network flow data (periodic connection analysis)", "IDS/IPS alerts", "Sysmon Event ID 3 (outbound connections)"],
        ),
        t(
            "T1071.001",
            "Application Layer Protocol: Web Protocols",
            "Command and Control",
            "Adversaries use HTTP and HTTPS to communicate with C2 infrastructure. Web protocols blend with normal browsing traffic and may use legitimate web services as intermediaries.",
            &[],
            "Monitor proxy logs for HTTP/HTTPS connections with beaconing intervals, unusual User-Agent strings, or connections to recently registered domains. Inspect JA3/JA3S fingerprints.",
            &["Web proxy logs (URL, User-Agent, JA3 hash)", "TLS certificate inspection logs", "DNS query logs for C2 domain resolution", "Network flow data (HTTP/S beaconing)", "Sysmon Event ID 3 (port 80/443 connections)"],
        ),
        t(
            "T1095",
            "Non-Application Layer Protocol",
            "Command and Control",
            "Adversaries use non-application layer protocols such as ICMP, UDP, or raw sockets for C2 communication to evade detection by tools focused on HTTP/DNS inspection.",
            &[],
            "Monitor for unusual ICMP traffic patterns or non-standard UDP communications from endpoints. Alert on raw socket usage by non-system processes.",
            &["Network flow data (ICMP/UDP anomalies)", "Firewall logs (non-standard protocol usage)", "IDS/IPS alerts for protocol anomalies", "Sysmon Event ID 3 (non-TCP connections)", "Packet capture analysis"],
        ),
        t(
            "T1572",
            "Protocol Tunneling",
            "Command and Control",
            "Adversaries tunnel C2 traffic within legitimate protocols such as SSH, DNS, or HTTP to bypass network security controls and blend with normal traffic patterns.",
            &[],
            "Monitor for DNS queries with high entropy or unusually long subdomains. Detect SSH tunnels by analyzing connection duration and data transfer patterns.",
            &["DNS query logs (tunneling indicators)", "Network flow data (long-duration connections)", "Proxy logs (HTTP tunnel detection)", "IDS alerts for tunneling signatures", "Sysmon Event ID 3 (SSH connections from non-admin users)"],
        ),
        t(
            "T1105",
            "Ingress Tool Transfer",
            "Command and Control",
            "Adversaries transfer tools and payloads from external systems into a compromised environment using C2 channels, web downloads, or other network protocols.",
            &[],
            "Monitor for file downloads by non-browser processes, especially to temp directories. Alert on certutil, bitsadmin, or PowerShell Invoke-WebRequest downloading executables.",
            &["Sysmon Event ID 11 (File Created from downloads)", "Sysmon Event ID 1 for download utilities (certutil, bitsadmin)", "Proxy logs (executable downloads)", "NTFS Zone.Identifier ADS (Mark of the Web)", "Prefetch for download utilities"],
        ),
        t(
            "T1197",
            "BITS Jobs",
            "Command and Control",
            "Adversaries abuse Windows Background Intelligent Transfer Service (BITS) to download or upload files and to create persistent jobs that survive reboots for C2 or payload delivery.",
            &[],
            "Monitor for bitsadmin.exe or PowerShell Start-BitsTransfer commands. Review BITS event log (Microsoft-Windows-Bits-Client/Operational) for suspicious download URLs.",
            &["Sysmon Event ID 1 for bitsadmin.exe", "Microsoft-Windows-Bits-Client/Operational log", "BITS job database (qmgr0.dat / qmgr1.dat)", "Prefetch for bitsadmin.exe", "Proxy logs for BITS download URLs"],
        ),

        // =====================================================================
        // ADDITIONAL TECHNIQUES (to reach 100+ entries)
        // =====================================================================

        // EXECUTION
        t(
            "T1047",
            "Windows Management Instrumentation",
            "Execution",
            "Adversaries abuse WMI to execute commands and payloads on local and remote systems. WMI provides a powerful interface for system administration that attackers leverage for execution and lateral movement.",
            &[],
            "Monitor for wmiprvse.exe spawning child processes and WMI event subscriptions. Review WMI-Activity/Operational log for suspicious queries and method invocations.",
            &["Sysmon Event ID 1 (wmiprvse.exe child processes)", "WMI-Activity/Operational Event ID 5857/5860/5861", "Sysmon Event ID 20/21 (WMI events)", "Prefetch for wmic.exe", "Windows Security Event ID 4688 for wmic.exe"],
        ),
        t(
            "T1204",
            "User Execution",
            "Execution",
            "Adversaries rely on users to execute malicious payloads by clicking links, opening attachments, or running downloaded files. Social engineering is used to convince users to take action.",
            &["T1204.001", "T1204.002"],
            "Monitor for process execution from user-accessible directories (Downloads, Desktop, Temp). Alert on executable launches from email clients or browser download folders.",
            &["Sysmon Event ID 1 (process from Downloads/Desktop)", "NTFS Zone.Identifier ADS (Mark of the Web)", "Prefetch for recently executed files", "Browser download history", "Email client process tree"],
        ),
        t(
            "T1204.001",
            "User Execution: Malicious Link",
            "Execution",
            "Adversaries trick users into clicking malicious links that lead to exploitation, credential harvesting, or payload download and execution.",
            &[],
            "Monitor browser process trees for child processes spawned after link navigation. Review proxy logs for redirects to malicious domains.",
            &["Browser process child creation (Sysmon Event ID 1)", "Web proxy logs (redirect chains)", "Browser history", "DNS query logs", "NTFS Zone.Identifier ADS"],
        ),
        t(
            "T1204.002",
            "User Execution: Malicious File",
            "Execution",
            "Adversaries trick users into opening malicious files such as Office documents with macros, executables disguised as documents, or script files delivered via email or web.",
            &[],
            "Monitor for Office applications spawning child processes (cmd.exe, powershell.exe, wscript.exe). Alert on executable files opened from email attachment temp directories.",
            &["Sysmon Event ID 1 (Office app child processes)", "AMSI logs for macro execution", "Prefetch for recently executed files", "NTFS $MFT for files in temp directories", "Office recent documents registry keys"],
        ),

        // PERSISTENCE
        t(
            "T1546",
            "Event Triggered Execution",
            "Persistence",
            "Adversaries establish persistence by registering code to execute when specific system events occur, such as logon events, WMI subscriptions, or application-specific triggers.",
            &["T1546.003", "T1546.015"],
            "Monitor for WMI event subscription creation and changes to event-triggered execution registry keys. Review Sysmon Event ID 19/20/21 for WMI persistence.",
            &["Sysmon Event ID 19/20/21 (WMI events)", "Registry keys for event triggers", "Windows Security Event ID 4657", "Autoruns output", "WMI repository analysis"],
        ),
        t(
            "T1546.003",
            "Event Triggered Execution: Windows Management Instrumentation Event Subscription",
            "Persistence",
            "Adversaries create WMI event subscriptions to execute payloads when specific events occur. WMI subscriptions persist across reboots and execute with SYSTEM privileges.",
            &[],
            "Monitor Sysmon Event ID 19 (WmiEventFilter), 20 (WmiEventConsumer), and 21 (WmiEventConsumerToFilter). Review the WMI repository for suspicious subscriptions.",
            &["Sysmon Event ID 19/20/21", "WMI repository (OBJECTS.DATA)", "WMI-Activity/Operational log", "Scrcons.exe process creation", "Autoruns WMI tab output"],
        ),
        t(
            "T1546.015",
            "Event Triggered Execution: Component Object Model Hijacking",
            "Persistence",
            "Adversaries hijack COM object references in the registry to execute malicious code when applications load specific COM objects, achieving persistence without modifying executables.",
            &[],
            "Monitor for new or modified CLSID/InprocServer32 registry entries pointing to DLLs in unusual locations. Compare COM registrations against known-good baselines.",
            &["Sysmon Event ID 13 (Registry Value Set for CLSID)", "HKCU\\Software\\Classes\\CLSID registry entries", "Sysmon Event ID 7 (DLL load from unusual paths)", "Autoruns output", "COM object registration comparison"],
        ),

        // DEFENSE EVASION
        t(
            "T1134",
            "Access Token Manipulation",
            "Defense Evasion",
            "Adversaries manipulate access tokens to operate under a different security context, enabling privilege escalation and defense evasion by impersonating other users or processes.",
            &["T1134.001"],
            "Monitor for token manipulation API calls via ETW. Alert on processes running with elevated tokens that were spawned by low-privilege processes.",
            &["Sysmon Event ID 1 (token elevation)", "Windows Security Event ID 4672 (Special Privileges Assigned)", "Windows Security Event ID 4624 (Logon with impersonation)", "ETW token manipulation traces", "Process token analysis"],
        ),
        t(
            "T1134.001",
            "Access Token Manipulation: Token Impersonation/Theft",
            "Defense Evasion",
            "Adversaries steal or duplicate access tokens from other processes to impersonate users with higher privileges. Named pipe impersonation and token duplication are common methods.",
            &[],
            "Monitor for DuplicateTokenEx and ImpersonateLoggedOnUser API calls. Alert on processes that acquire tokens from higher-privilege processes.",
            &["Windows Security Event ID 4672 (Special Privileges)", "Sysmon Event ID 10 (ProcessAccess for token theft)", "ETW Security-Auditing provider", "Process integrity level analysis", "Named pipe creation and impersonation events"],
        ),
        t(
            "T1562",
            "Impair Defenses",
            "Defense Evasion",
            "Adversaries disable or modify security tools and logging mechanisms to prevent detection. This includes disabling antivirus, stopping logging services, and modifying firewall rules.",
            &["T1562.001", "T1562.004"],
            "Monitor for security service state changes and attempts to modify security tool configurations. Alert on tamper protection bypass attempts.",
            &["Windows System Event ID 7036 (Service state changes)", "Windows Defender event logs", "Sysmon Event ID 1 for sc.exe / net.exe stop commands", "Security tool tamper protection alerts", "Group Policy modification logs"],
        ),
        t(
            "T1562.001",
            "Impair Defenses: Disable or Modify Tools",
            "Defense Evasion",
            "Adversaries disable security tools such as antivirus, EDR agents, and host firewalls by stopping services, uninstalling agents, or modifying configurations.",
            &[],
            "Monitor for security service termination events and attempts to uninstall security software. Alert on processes that stop or delete security-related services.",
            &["Windows System Event ID 7036 (security service stopped)", "Sysmon Event ID 1 for sc.exe stop/delete on security services", "Windows Defender Event ID 5001 (Real-time Protection disabled)", "Application uninstall logs", "Registry changes to security service startup type"],
        ),
        t(
            "T1562.004",
            "Impair Defenses: Disable or Modify System Firewall",
            "Defense Evasion",
            "Adversaries disable or modify the system firewall to allow unrestricted network communication for C2 traffic, lateral movement, or data exfiltration.",
            &[],
            "Monitor for netsh advfirewall set commands and PowerShell Set-NetFirewallProfile. Alert on firewall profile changes that disable all profiles.",
            &["Sysmon Event ID 1 for netsh.exe advfirewall", "Windows Firewall Event ID 2003 (Profile Changed)", "PowerShell logs for Set-NetFirewallProfile", "Registry changes to firewall policy keys", "Prefetch for netsh.exe"],
        ),

        // CREDENTIAL ACCESS (additional)
        t(
            "T1110",
            "Brute Force",
            "Credential Access",
            "Adversaries systematically guess credentials using brute force, password spraying, or credential stuffing to gain access to accounts when passwords are unknown.",
            &["T1110.003"],
            "Monitor for high volumes of failed authentication attempts (Event ID 4625) from single sources. Alert on password spraying patterns where one password is tried against many accounts.",
            &["Windows Security Event ID 4625 (Failed Logon)", "Windows Security Event ID 4771 (Kerberos Pre-Auth Failed)", "Account lockout events (Event ID 4740)", "VPN/Remote access authentication logs", "Azure AD sign-in failure logs"],
        ),
        t(
            "T1110.003",
            "Brute Force: Password Spraying",
            "Credential Access",
            "Adversaries try a single commonly-used password against many accounts to avoid triggering account lockout policies that would result from traditional brute force attacks.",
            &[],
            "Monitor for patterns where a single password hash or failed attempt is seen across many accounts in a short timeframe. Correlate failed logons by source IP and time window.",
            &["Windows Security Event ID 4625 (many accounts, one source)", "Windows Security Event ID 4771 (Kerberos failures)", "Azure AD risky sign-in detections", "Account lockout correlation analysis", "Authentication log time-series analysis"],
        ),
    ]
}
